### ISSUE TITLE
Enhancement: execute command on all / selected devices

### ISSUE THREAD

**Issue by iMarkus** [hassio-addons/addon-tasmoadmin#10]
First of all great work!

It would be very nice to provide a functionality to execute a command on all / selected devices. For example to change the timezone.

Best regards,
iMarkus

**Comment by ascillato** [comment]
Hi

That option is already there in last version. Just select all devices. Thanks

**Comment by frenck** [comment]
yes, it is already added. 👍

**Comment by iMarkus** [comment]
Found it. Perfect job guys!
