### ISSUE TITLE
JSON ERROR 4 issue

### ISSUE THREAD

**Issue by lumper5** [hassio-addons/addon-tasmoadmin#101]
# Problem/Motivation

I can reach the switch device at its URL, but HA and TA can't communicate with it. I can toggle, get stats & etc. by the URL, but not inside Home Assistant.  I've restarted the device virtually and manually (unplugged), reissued setoption 19 and everything else I can think of.  The device was working for months, but became unavailable yesterday at 3 p.m. my local time.

Could not reach device. Please try again. This happens if the device is restarting or there were too many requests.
JSON ERROR => 4: Syntax error
Please copy the whole error message and copy it in a new issue on GitHub. Somehow the Tasmota Firmware answered a wrong formatted JSON string which needs to get adjusted in TasmoAdmin.

Device not found

JSON ERROR => 4: Syntax error
Please copy the whole error message and copy it in a new issue on GitHub. Somehow the Tasmota Firmware answered a wrong formatted JSON string which needs to get adjusted in TasmoAdmin.
JSON Answer => {"Status":{"Module":0,"DeviceName":"SW_HotWater","FriendlyName":["Hot Water"],"Topic":"tasmota_251A54","ButtonTopic":"0","Power":1,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0},"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://ota.tasmota.com/tasmota/tasmota.bin","RestartReason":"Software/System restart","Uptime":"0T00:00:42","StartupUTC":"","Sleep":50,"CfgHolder":4617,"BootCount":97,"BCResetTime":"2020-07-30T01:25:11","SaveCount":1935,"SaveAddress":"F8000"},"StatusFWR":{"Version":"9.0.0.1(tasmota)","BuildDateTime":"2020-10-10T10:26:55","Boot":31,"Core":"2_7_4_3","SDK":"2.2.2-dev(38a443e)","CpuFrequency":80,"Hardware":"ESP8266EX","CR":"382/699"},"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["GetGo2",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["000A8009","2805C8000100060000005A00000000000000","00000200","00006000","00000000"]},"StatusMEM":{"ProgramSize":599,"Free":404,"Heap":25,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"144068","FlashFrequency":40,"FlashMode":3,"Features":["00000809","8FDAE797","04368001","000000CF","010013C0","C000F981","00004004","00000000"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,27,29,30,35,37","Sensors":"1,2,3,4,5,6"},"StatusNET":{"Hostname":"tasmota_251A54-6740","IPAddress":"192.168.1.200","Gateway":"192.168.1.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.1.3","Mac":"2C:F4:32:25:1A:54","Webserver":2,"WifiConfig":4,"WifiPower":17.0},"StatusMQT":{"MqttHost":"192.168.1.48","MqttPort":1883,"MqttClientMask":"D,"StatusTIM":{"UTC":"1970-01-01T00:00:55","Local":"1970-01-01T00:00:55","StartDST":"1970-01-01T00:00:00","EndDST":"1970-01-01T00:00:00","Timezone":"+00:00","Sunrise":"20:13","Sunset":"05:47"},"StatusPTH":{"PowerDelta":[0,0,0],"PowerLow":0,"PowerHigh":0,"VoltageLow":0,"VoltageHigh":0,"CurrentLow":0,"CurrentHigh":0},"StatusSNS":{"Time":"1970-01-01T00:00:55","ENERGY":{"TotalStartTime":"2020-07-30T01:25:11","Total":11.941,"Yesterday":0.351,"Today":0.094,"Power":24,"ApparentPower":25,"ReactivePower":6,"Factor":0.97,"Voltage":120,"Current":0.206}},"StatusSTS":{"Time":"1970-01-01T00:00:55","Uptime":"0T00:00:42","UptimeSec":42,"Heap":25,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":65,"MqttCount":0,"POWER":"ON","Wifi":{"AP":1,"SSId":"GetGo2","BSSId":"B2:4E:26:73:1F:79","Channel":9,"RSSI":80,"Signal":-60,"LinkCount":1,"Downtime":"0T00:00:36"}}}}

**Comment by frenck** [comment]
Please report your issue with TasmoAdmin itself.

Add-ons wrap existing software, in this case TasmoAdmin. From an add-on perspective, there is not much I can do.
