### ISSUE TITLE
setoption80 1 not reporting

### ISSUE THREAD

**Issue by xHirscHx** [hassio-addons/addon-tasmoadmin#102]
tasmota latest firmware 8.5.1 when i setotion80 1 (tasmota curtains) the device stops reporting in tasmotadmin
I rest device back to defaults it connects fine when i try to re add it it with setoption80 1 on gives me this error code

Device not found

JSON ERROR => 4: Syntax error
Please copy the whole error message and copy it in a new issue on GitHub. Somehow the Tasmota Firmware answered a wrong formatted JSON string which needs to get adjusted in TasmoAdmin.
JSON Answer => {"Status":{"Module":23,"DeviceName":"Cjs_curtains_2_tas","FriendlyName":["Tasmota","Tasmota2","Tasmota3","Tasmota4"],"Topic":"tasmota_C2240D","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0},"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://ota.tasmota.com/tasmota/release/tasmota.bin","RestartReason":"Power On","Uptime":"0T00:01:18","StartupUTC":"2020-11-05T03:40:44","Sleep":50,"CfgHolder":4617,"BootCount":17,"BCResetTime":"2020-11-03T01:27:48","SaveCount":85,"SaveAddress":"F7000"},"StatusFWR":{"Version":"8.5.1(tasmota)","BuildDateTime":"2020-10-02T10:09:47","Boot":31,"Core":"2_7_4_1","SDK":"2.2.2-dev(38a443e)","CpuFrequency":80,"Hardware":"ESP8285","CR":"384/699"},"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["XXXXX",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["0000C009","2805C8000100060000005A00000000000000","40000000","00006000","00000000"]},"StatusMEM":{"ProgramSize":596,"Free":404,"Heap":26,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"144051","FlashFrequency":40,"FlashMode":3,"Features":["00000809","8FDAE797","04368001","000000CD","010013C0","C000F981","00004004","00000000"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,27,29,30,35,37","Sensors":"1,2,3,4,5,6"},"StatusNET":{"Hostname":"Cjs_curtains_2_tas","IPAddress":"192.168.1.205","Gateway":"192.168.1.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.1.1","Mac":"E0:98:06:C2:24:0D","Webserver":2,"WifiConfig":4,"WifiPower":17.0},"StatusMQT":{"MqttHost":"","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_C2240D","MqttUser":"DVES_USER","MqttCount":0,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30},"StatusTIM":{"UTC":"2020-11-05T03:42:02","Local":"2020-11-05T04:42:02","StartDST":"2020-03-29T02:00:00","EndDST":"2020-10-25T03:00:00","Timezone":"+01:00","Sunrise":"07:44","Sunset":"17:22"},"StatusSNS":{"Time":"2020-11-05T04:42:02","Shutter1":{"Position":0,"Direction":0,"Target":0},"Shutter2":{"Position":100,"Direction":0,"Target":100}},"StatusSTS":{"Time":"2020-11-05T04:42:02","Uptime":"0T00:01:18","UptimeSec":78,"Heap":26,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":0,"POWER1":"OFF","POWER2":"OFF","POWER3":"OFF","POWER4":"OFF","Wifi":{"AP":1,"SSId":"XXXXX","BSSId":"5E:BA:BA:6E:E3:58","Channel":6,"RSSI":100,"Signal":-27,"LinkCount":1,"Downtime":"0T00:00:05"}},"StatusSHT":{"SHT0":{"Relay1":1,"Relay2":2,"Open":100,"Close":100,"50perc":50,"Delay":0,"Opt":"0000","Calib":"300:500:700:900:1000","Mode":"0"}},{"SHT1":{"Relay1":3,"Relay2":4,"Open":254,"Close":240,"50perc":50,"Delay":0,"Opt":"0000","Calib":"300:500:700:900:1000","Mode":"0"}}}}

×
Device IP

**Comment by frenck** [comment]
This is a problem with TasmoAdmin itself (the application the add-on wraps).

Please report your issue upstream with the main project. If they fix it, the add-on will be updated as well.

Thanks 👍
