### ISSUE TITLE
Failed to install 64bit Version

### ISSUE THREAD

**Issue by duesseldorferjung** [hassio-addons/addon-tasmoadmin#103]
Good Day Everyone,
I am running the 64bit Hass Version on my Raspberry and installation of the addon fails.

> 404 Client Error: Not Found ("no such image: hassioaddons/sonweb-aarch64:0.13.1: No such image: hassioaddons/sonweb-aarch64:0.13.1")

Can I help out with any additional data?

**Comment by frenck** [comment]
![image](https://user-images.githubusercontent.com/195327/98659948-fcbe2480-2344-11eb-8341-b37378946911.png)


It exists. Not much I can do about it from my end.
Make sure to check all available logs (e.g., Supervisor/System logs)

**Comment by duesseldorferjung** [comment]
That is an amazing response time 👍 Removing and adding the repository in the Add-On Store did the trick.

**Comment by frenck** [comment]
Glad you got it resolved sir! 👍
