### ISSUE TITLE
Password Reset

### ISSUE THREAD

**Issue by pnsiva** [hassio-addons/addon-tasmoadmin#105]
# Problem/Motivation

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by pnsiva** [comment]
Was working fine until I have to change my router and my IP changed. Home assistant is now back working. Tasmoadmin is not working. Two Issues
1) How to reset the Tasmoadmin password
2) How to do a clean uninstall and re-install. Removing the plugin doesn't remove everything. It still remembers the userid/ password.

**Comment by frenck** [comment]
Uninstall removes all data. There is no control for the add-on over that.
There is no password recovery option.

**Comment by ascillato** [comment]
> Removing the plugin doesn't remove everything. It still remembers the userid/ password.

In the first page fo TasmoAdmin when it starts for the first time, it asks you to register a new USER/PASSWORD.
You should uninstall TasmoAdmin, Install it again, and in the first page, just enter the user/password you want.
