### ISSUE TITLE
not working after update to latest version 0.21

### ISSUE THREAD

**Issue by gnkarn** [hassio-addons/addon-tasmoadmin#11]
tested on chrome , and safari ,
 was working perfect before update 
it doesn not open the first screen 

error:

Parse error: syntax error, unexpected '' => '' (T_CONSTANT_ENCAPSED_STRING) in /var/www/tasmoadmin/tasmoadmin/includes/Config.php(65) : eval()'d code on line 3

**Comment by frenck** [comment]
This is not an issue with the add-on. Please create an issue on the upstream project:

<https://github.com/reloxx13/TasmoAdmin>

To work around the issue, you'd need to uninstall/install the add-on.

**Comment by gnkarn** [comment]
ok
