### ISSUE TITLE
cannot reach tasmoadmin

### ISSUE THREAD

**Issue by Sloth-on-meth** [hassio-addons/addon-tasmoadmin#120]
# Problem/Motivation

tasmoadmin does not show up 

## Expected behavior

tasmoadmin sdisplaying
## Actual behavior

tasmoadmin starts, no issues in log, but does not actually show up when i click the tab in HA. just get grey screen

## Steps to reproduce

not sure

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
Please provide information... like just a "It doesn't work" I can't fix.

For example: Add-on configuration, system information, versions of things, add-on logs, supervisor logs, error in the browser console?

**Comment by tsvsj** [comment]
Same issue here. The port is not published from the container to the host. Requests are runnting into timeouts. It was working until the IP range scan was completed and all discovered devices were added.

**Config**
```
ssl: false
certfile: fullchain.pem
keyfile: privkey.pem
log_level: trace
```

**Add-on Log**
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-tasmoadmin: applying... 
[fix-attrs.d] 01-tasmoadmin: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: TasmoAdmin
 Centrally manage all your Sonoff-Tasmota devices
-----------------------------------------------------------
 Add-on version: 0.14.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 5.10  (amd64 / qemux86-64)
 Home Assistant Core: 2021.2.1
 Home Assistant Supervisor: 2021.01.7
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to TRACE
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[03:00:35] TRACE: bashio::config.true: ssl
[03:00:35] TRACE: bashio::config: ssl
[03:00:35] TRACE: bashio::jq: /data/options.json if (.ssl == null) then
            null
        elif (.ssl | type == "string") then
            .ssl // empty
        elif (.ssl | type == "boolean") then
            .ssl // false
        elif (.ssl | type == "array") then
            if (.ssl == []) then
                empty
            else
                .ssl[]
            end
        elif (.ssl | type == "object") then
            if (.ssl == {}) then
                empty
            else
                .ssl
            end
        else
            .ssl
        end
[03:00:35] TRACE: bashio::var.true: false
[03:00:35] TRACE: bashio::config.true: ssl
[03:00:35] TRACE: bashio::config: ssl
[03:00:35] TRACE: bashio::jq: /data/options.json if (.ssl == null) then
            null
        elif (.ssl | type == "string") then
            .ssl // empty
        elif (.ssl | type == "boolean") then
            .ssl // false
        elif (.ssl | type == "array") then
            if (.ssl == []) then
                empty
            else
                .ssl[]
            end
        elif (.ssl | type == "object") then
            if (.ssl == {}) then
                empty
            else
                .ssl
            end
        else
            .ssl
        end
[03:00:35] TRACE: bashio::var.true: false
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] tasmoadmin.sh: executing... 
[03:00:35] TRACE: bashio::fs.directory_exists: /data/tasmoadmin
[03:00:35] DEBUG: Symlinking data directory to persistent storage location...
[cont-init.d] tasmoadmin.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[03:00:35] TRACE: bashio::net.wait_for 9001
[03:00:35] INFO: Starting PHP-FPM server...
[03:00:36] INFO: Starting NGinx server...
```

In the core log I found a stack trace, mentioning that dependency `mqtt` couldn't be fulfilled. Unfortunately that entry is already gone... :-(

**Comment by frenck** [comment]
```
[03:00:35] TRACE: bashio::net.wait_for 9001
[03:00:35] INFO: Starting PHP-FPM server...
[03:00:36] INFO: Starting NGinx server...
```

That indicates the add-on has started successfully.

MQTT is not a dependency of this add-on.

**Comment by Sloth-on-meth** [comment]
> Please provide information... like just a "It doesn't work" I can't fix.
> 
> For example: Add-on configuration, system information, versions of things, add-on logs, supervisor logs, error in the browser console?

I learned that supplying system info gets my issues closed as unsupported, so I'm gonna say debian with supervised...

Anyway, default configuration on the add-on. The addon starts properly, but isn't reachable. No browser errors, just a gray empty screen when i click the tasmoadmin tab in the sidebar

**Comment by frenck** [comment]
> I learned that supplying system info gets my issues closed as unsupported, so I'm gonna say debian with supervised...

Now I have to close it because there is no information. I have not completed a course as a fortune teller and I do not own a crystal ball either.

**Comment by Sloth-on-meth** [comment]
Alright.

Ubuntu 20.04 LTS .
HA supervised 
core-2021.2.1
supervisor-2021.02.2

Config:
```
ssl: true
certfile: fullchain.pem
keyfile: privkey.pem
log_level: debug
```

![Screenshot_20210206-123543](https://user-images.githubusercontent.com/43210224/107117068-df332500-6877-11eb-98ff-1c820d46ddc5.jpg)

**Comment by Sloth-on-meth** [comment]
> > I learned that supplying system info gets my issues closed as unsupported, so I'm gonna say debian with supervised...
> 
> Now I have to close it because there is no information. I have not completed a course as a fortune teller and I do not own a crystal ball either.
> 
> Please provide the requested information.

Also, i apologize, bad day

**Comment by frenck** [comment]
Right, this is over SSL. By the looks, you are using an iFrame panel in Home Assistant, right now?

Does it work without the iFrame panel (e.g., accessing it directly)?

**Comment by tsvsj** [comment]
> ```
> [03:00:35] TRACE: bashio::net.wait_for 9001
> [03:00:35] INFO: Starting PHP-FPM server...
> [03:00:36] INFO: Starting NGinx server...
> ```
> 
> That indicates the add-on has started successfully.
> 
> MQTT is not a dependency of this add-on.

Don't want to disturb the conversation, but I've never said, that the container isn't running. Just the port seems not to be exposed...

Is it possible, that MQTT is a requirement from TasmotaAdmin itself?

**Comment by Sloth-on-meth** [comment]
> Right, this is over SSL. By the looks, you are using an iFrame panel in Home Assistant, right now?
> 
> Does it work without the iFrame panel (e.g., accessing it directly)?

Sorry for not mentioning that - port directly does work. And gives no SSL errors

**Comment by frenck** [comment]
>  but I've never said, that the container isn't running.

Neither did I say that.

>  Just the port seems not to be exposed...

This is not a normal Docker environment.

> Is it possible, that MQTT is a requirement from TasmotaAdmin itself?

No, it is not. There is no MQTT involved here.

**Comment by frenck** [comment]
> Sorry for not mentioning that - port directly does work. And gives no SSL errors

Nice! That is a good hint. Will get back to this. 👍

**Comment by tsvsj** [comment]
> This is not a normal Docker environment.

Ok. Now I'm stuck. Neither direct access and iFrame work for me.

**Comment by sinclairpaul** [comment]
@Sloth-on-meth Can you confirm your iFrame configuration?, as you mention SSL errrors.  Is it configured to access using SSL?

From a quick test there doesn't seem to be an issue with CORS (although there are some errors found).

**Comment by Sloth-on-meth** [comment]
> @Sloth-on-meth Can you confirm your iFrame configuration?, as you mention SSL errors. Is it configured to access using SSL?
> 
> From a quick test there doesn't seem to be an issue with CORS (although there are some errors found).

I'm just using the Addon in the Hassio add-ons thing. The config i had above is the addon config.

**Comment by sinclairpaul** [comment]
From your screenshot, you are accessing TasmoAdmin from an iFrame, as you mentioned earlier.

You will see this behavior if your iframe is configured with http in your configuration.yaml, and you access HA via https (you can't iframe a non secure site into a secure one).

**Comment by Sloth-on-meth** [comment]
![Screenshot_20210206-170702](https://user-images.githubusercontent.com/43210224/107123427-c63d6a80-689d-11eb-84fa-ef85eda2d3cd.jpg)
I use this, a hassio addon

**Comment by sinclairpaul** [comment]
What do you have in your configuration.yaml to create the iframe, for example
```
panel_iframe:
  tasmoadmin:
    title: TasmoAdmin
    icon: mdi:lightbulb-on
    url: https://ha.mydomain.com:9541
```

**Comment by Sloth-on-meth** [comment]
Sorry for the confusion but there's nothing in my configuration.yaml for this , that's just the "show in sidebar" Option in the addon setting

**Comment by frenck** [comment]
@Sloth-on-meth  This add-on does not have a "Show in Sidebar" option.... as this add-on does not have or support Ingress:

![image](https://user-images.githubusercontent.com/195327/107123887-8af06b00-68a0-11eb-8d87-65bcd011cfbb.png)

**Comment by Sloth-on-meth** [comment]
Oh my god i feel so dumb.i apparently added it to my config a century ago, with, you guessed it, HTTP. I just changed it to https://domain:9541 and it works!

Sorry for wasting you guy's time 🥺

**Comment by frenck** [comment]
haha well, I'm glad it is resolved @Sloth-on-meth! 👍

**Comment by sinclairpaul** [comment]
Glad you have it resolved :) , you may want to also look at the documentation for TasmoAdmin, around OTA and SSL...

**Comment by Sloth-on-meth** [comment]
Yeah, thanks for the help! I will OTA with ssl disabled haha
