### ISSUE TITLE
Tasmoadmin firmware update

### ISSUE THREAD

**Issue by nasked** [hassio-addons/addon-tasmoadmin#121]
Firmware update after select files and push next button. 413 nginx error.

**Comment by frenck** [comment]
Hi there, could you provide more than a 1 line issue description?

What did you do? What settings do you have? What versions of like a lot? Anything in some logs? Reproduction steps?

**Comment by nasked** [comment]
Forget it Frenck. I'd resolved it. Problem was a wrong tastmota file..
