### ISSUE TITLE
"panel_iframe" doesn't work (X-Frame-Options issue)

### ISSUE THREAD

**Issue by cannondale0815** [hassio-addons/addon-tasmoadmin#125]
# Problem/Motivation

When including tasmoadmin in the Home Assistant panel_iframe, it doesn't let you go past the authentication dialog, even when entering the correct credentials. This seems to be an issue with X-Frame-Options in the header. I can overcome this issue by creating an Nginx config that uses "proxy_hide_header X-Frame-Options".

## Expected behavior

Being able to log into TasmoAdmin in panel_iframe.

## Actual behavior

Unable to get past login screen.

## Steps to reproduce

1) Include TasmoAdmin in HA panel_iframe.
2) Try to log into TasmoAdmin
3) You won't get past login screen

## Proposed changes

Provide a way to hide X-Frame-Options in header.

**Comment by sinclairpaul** [comment]
Does your iframe URL match what you are accessing HA on?

**Comment by cannondale0815** [comment]
Yes, the URL is identical. When accessing it directly, I can log in without issues. When accessing the same URL through the iframe panel (as configured in my configuration.yaml), after entering credentials and hitting the login button, I am looking at the same login screen again where it asks me for my credentials again. 
When wrapping the TasmoAdmin URL inside my own Nginx configuration with the X-Frame-Options setting (as described above), logging into TasmoAdmin works inside the iframe panel.
