### ISSUE TITLE
ESPHome Warning

### ISSUE THREAD

**Issue by helmbrandt** [hassio-addons/addon-tasmoadmin#126]
I get this in supervisor Logs with TasmoAdmin installed,

seems to be fixed with:

https://github.com/esphome/issues/issues/1806

But I dont know how that ties in to tasmoadmin. Im new to this

```21-02-14 10:44:19 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of ESPHome
21-02-14 10:44:19 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of ESPHome

**Comment by frenck** [comment]
Please report that with ESPHome, this is the TasmoAdmin addon repository.
