### ISSUE TITLE
AutoScan error

### ISSUE THREAD

**Issue by stolek5** [hassio-addons/addon-tasmoadmin#13]
After click on on AutoScan I didn't get "AutoScan scanning..." pop-up window. 
But after a while in scan results it found 2 devices ( have only 1 connected during test)

Error:
![image](https://user-images.githubusercontent.com/38689961/41912118-f103360a-794e-11e8-98d3-d281c3cbcfd9.png)

1st device
![image](https://user-images.githubusercontent.com/38689961/41912144-13213d9a-794f-11e8-8217-b8855e89f132.png)

2nd device - ok

**Comment by frenck** [comment]
I'm closing your issue since it looks misplaced. This is the issue tracker for the add-on, not TasmoAdmin itself. (Which seems to be the root cause of this issue).

You can fing the upstream repo here: https://github.com/reloxx13/TasmoAdmin

Thanks!
