### ISSUE TITLE
Repostitory structure for v0.14.0 is not compliant

### ISSUE THREAD

**Issue by trynqz** [hassio-addons/addon-tasmoadmin#132]
# Problem/Motivation

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by trynqz** [comment]
Hi,
I can not find this addon in hasc integrations list or add it manually. it was avaliable in previous ha version. Now I'm using core-2021.3.1 hacs 1.11.3

**Comment by frenck** [comment]
This is an add-on, not an integration.
