### ISSUE TITLE
external instead of internal url to access web console page

### ISSUE THREAD

**Issue by aladin2000** [hassio-addons/addon-tasmoadmin#137]
# Problem/Motivation
web access is not able to use local resolution 

> (Why the issue was filed)

## Expected behavior
access to internal url of ha port 9541  
> (What you expected to happen)
access to internal url of ha 

## Actual behavior
external url not found for HA 
> (What actually happened)

## Steps to reproduce
access to web page from the configuration of tasmadmin  

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)
I used the ip adress instead of url given by app.... but not possible to keep the workaround for the long time

**Comment by frenck** [comment]
The issue is unclear to me? Could you clarify what you are trying to do, as in, the add-on is available on port 9541...

**Comment by aladin2000** [comment]
Hi
I wanted to have acces to webgui of the Addon and the used URL seems to be external URL and not the internal url
So using the fonction of accessing the web interface
the proposed URL is HTTPS://url_domain_hass:9541 instead of
HTTPS://ip_of_hass:9541  as expected to Access webgui from my lan

28 mars 2021 13:08:48 Franck Nijhof ***@***.***>:

**Comment by frenck** [comment]
I'm confused. There is no internal or external URL involved here in any way.
The add-on binds to port 9541 of your device. How you expose it, is up to you.

**Comment by aladin2000** [comment]
Hi
I am used to Access my ha instance with either IP or dns adress from my LAN
If i connect with IP, then the Addon use the same link but if i use named server then as the port 9541 is not visible from external of my router  then i cant access to gui
I am forced to reconnect using IP adresse instead
It is not the case for others addons
Hope i explain correctly

Regards

28 mars 2021 17:31:01 Franck Nijhof ***@***.***>:

**Comment by frenck** [comment]
Aah, well some add-ons provide Ingress (which pulls them into the Home Assistant interface). This add-on does not (and cannot) provide that. It provides a port. Making that port available is up to you, not the add-on.

**Comment by aladin2000** [comment]
Ok thks

28 mars 2021 17:47:12 Franck Nijhof ***@***.***>:
