### ISSUE TITLE
Tasmoadmin is stuck (will not uninstall completely?)

### ISSUE THREAD

**Issue by pcopa** [hassio-addons/addon-tasmoadmin#15]
# Problem/Motivation

> Tasmoadmin is stuck on home screen with only "uninstall" and "start". 

![image](https://user-images.githubusercontent.com/15312957/42735167-699a090e-881d-11e8-957c-6c68c044b5ed.png)

## Expected behavior

>Expected it to uninstall completely.

## Actual behavior

> The same screen comes back on after uninstall, even after HA.restart and Pi reboot.

## Steps to reproduce

>This was a clean Hassio install on a new RPi3B+ and after I could not login to the web ui, desided to uninstall and reinstall.

## Proposed changes

> None. Keep up the good work. I've been using it for 3 Months and loving it.

**Comment by frenck** [comment]
This issue is caused by an problem upstream:

home-assistant/hassio#568

**Comment by frenck** [comment]
This issue has been solved upstream.
You should now be able to remove it normally again.
