### ISSUE TITLE
Automatic OTA download can't download binaries

### ISSUE THREAD

**Issue by McGiverGim** [hassio-addons/addon-tasmoadmin#156]
# Problem/Motivation

If I go to the OTA update, and select automatic, an error appears in the page saying that it cannot download binaries from GitHub.

![image](https://user-images.githubusercontent.com/2673520/117679227-5f876000-b1b0-11eb-984e-5854ca0b908b.png)

## Expected behavior

To download latest 9.4.0 version.

## Actual behavior

It does not download latest version, if I press install it seems to reinstall old 9.3.1 version (maybe cached in the addon?)

## Steps to reproduce

Press automatic when selecting the OTA update.

## Proposed changes

Fix the problem when downloading from Github.

**Comment by McGiverGim** [comment]
It does not seem the same issue at all. One is when downloading binaries automatically from Github. The other is when uploading the binaries to the device.

**Comment by sinclairpaul** [comment]
Either way, the addon wraps the TasmoAdmin software, so the issue would need to be logged upstream.
