### ISSUE TITLE
Firmware updates blocked by nginx deny rule.

### ISSUE THREAD

**Issue by shift** [hassio-addons/addon-tasmoadmin#162]
# Problem/Motivation

Firmware updates are unable to happen due to the nginx rule

        location /data/ {
            deny all;
        }

## Expected behavior

Firmware updates work
## Actual behavior

nginx throws a 403 error
## Steps to reproduce

Try and perform an update using TasmotaAdmin as the OTA URL
## Proposed changes

        location /data/ {
            deny all;
        }

        location /data/firmwares/ {
            allow all;
        }

Seems to resolve the issue but may not be the safest.

**Comment by frenck** [comment]
It is already in the file, above the /data/ location.
