### ISSUE TITLE
FW update report always says "successful" but nothing works!

### ISSUE THREAD

**Issue by oywino** [hassio-addons/addon-tasmoadmin#174]
# Problem/Motivation
I have tried modifying all kinds of parameters possible in TasmoAdmin. And even if I deliberately add mumbo-jumbo crazy IP adresses and port numbers and FW versions, it is always happy-go-lucky and reports update DONE.
> (Why the issue was filed)
It seems TasmoAdmin never bothers to actually check if the update truly was successful or not. It just says "DONE" every time.
## Expected behavior

> (What you expected to happen)
I was expecting to get an error message (at least) if the update fails.
## Actual behavior
![image](https://user-images.githubusercontent.com/18447119/123327669-f7f85a80-d53a-11eb-94b1-ccc1a3c11d3f.png)

> (What actually happened)
Nothing!
## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)
I tried browsing to `http://192.168.0.8:8123/data/firmwares/tasmota.bin` but all I got was a 404 error.
I'm sure I'm doing something wrong, but what?
TasmoAdmin seems to work "as such" cause I can see all my devices and play with them OK.

**Comment by sinclairpaul** [comment]
The default port for the addon would be 9541 (8123 is HA).

Does ```http://192.168.0.8:9541/data/firmwares/tasmota.bin``` provide something?

Why the app reports the firmware update is complete would likely need to be raised at the TasmoAdmin repo itself.

**Comment by oywino** [comment]
Thanks for stopping by @sinclairpaul 
But no, `http://192.168.0.8:9541/data/firmwares/tasmota.bin` just giver the "Page not found" message.
And the result after a flash attempt is exactly the same as before; DONE, but nothing is done.

Can you please provide a link to the docs where you found that port number? (Even though it too seems to be incorrect)

**Comment by sinclairpaul** [comment]
The port is configurable on the addon/Configuration tab:
![image](https://user-images.githubusercontent.com/24625998/123419138-dd989e00-d587-11eb-8abc-6cf1f77c904e.png)

The default is 9541:

![image](https://user-images.githubusercontent.com/24625998/123419212-f3a65e80-d587-11eb-85c3-02a6a2223e6a.png)


It will also be shown in the URL, when you access the application via the Open Web UI button.  If you configured a panel to access as per the documentation, it would also be included there.

https://github.com/hassio-addons/addon-tasmoadmin/blob/main/tasmoadmin/DOCS.md

**Comment by oywino** [comment]
Again, thank you for helping.
The thing is, you see - that I don't use the "add-on".  My TasmoAdmin instance runs separately in on a Linux Server in a Docker Container.  It is often frustrating that all too often, people automatically assume that everyone is running Hass.io (HA-OS).
Anyway, you did point me in the right direction. Changing to the IP of the Linux Server and the port of TasmoAdmin (which in my case was 6080), and it finally began working - almost.
Automatic download and update now works, for devices which are directly upgradable to the latest 9.5.0, but older versions fail. Downloading an old sonoff.minimal.bin and manually loading it into TasmoAdmin doesn't seem to work. It still tries to flash tasmota.bin. Whatever file I load, it seems to ignore it. The link always point to same URL during update.
And I am not able to locate where the downloaded firmware images are stored. The link http://192.168.0.19:6080/data/firmwares/ doesn't take me anywhere, but "Page not found".

**Comment by sinclairpaul** [comment]
> The thing is, you see - that I don't use the "add-on".

> It is often frustrating that all too often, people automatically assume that everyone is running Hass.io (HA-OS).

This is the repo for the addon where you have created the issue.  As you do not run it there isn't much we can do to help.

The TasmoAdmin application repo is at https://github.com/reloxx13/TasmoAdmin

**Comment by oywino** [comment]
Oh, Oh - I'm so sorry - My bad 😮
I will relocate myself asap. Thanks for your kind advice, Sir.
