### ISSUE TITLE
Not finding Wemos nodes with multiple 18B20 reading errors

### ISSUE THREAD

**Issue by smokey1300** [hassio-addons/addon-tasmoadmin#18]
# Problem/Motivation

> I have a Wemos D1 mini with 8-18B20 sensors. Using auto detect it doesn't find node. 

## Expected behavior

> I assume but not sure is this related to the format of the message from my Wemos?

## Actual behavior

> During auto scan doesn't appear. When I try to enter manually I get a huge error dialog and no connection.

## Steps to reproduce

> Need a Wemos with multiple sensors.

## Proposed changes

> Looks like the message is not standard when you have multiple sensors. Could be a firm
![screenshot 20](https://user-images.githubusercontent.com/23421956/43358965-42c67272-9268-11e8-85c5-98418ae9614d.png)
![screenshot 21](https://user-images.githubusercontent.com/23421956/43358967-499e9e94-9268-11e8-89fc-f8c25d97317c.png)

ware issue.

**Comment by xbmcnut** [comment]
Same behaviour on Sonoff basic. Have three devices with Tasmota 6.1.1; Sonoff basic, Sonoff Dual and Sonoff POW. Sonoff basic has DS18x20 sensor added and it does not get found in TasmoAdmin and reports an error _JSON ERROR => 4: Syntax_ error as above.

**Comment by xbmcnut** [comment]
I have not.

**Comment by tjorim** [comment]
Please report the issue here: https://github.com/reloxx13/TasmoAdmin
As it's probably TasmoAdmin-related and not specifically to this add-on.

**Comment by xbmcnut** [comment]
Will do.
