### ISSUE TITLE
ERR_SSL_VERSION_OR_CIPHER_MISMATCH

### ISSUE THREAD

**Issue by brinzlee** [hassio-addons/addon-tasmoadmin#199]
Anybody come across this message…
“The client and server don’t support a common SSL protocol version or cipher suite.”
I’m getting this when trying to open the WebUI from TasmoAdmin. I've tried chrome and safari, Its been working fine for ages and now I can’t start it, I have deleted duckdns and reinstalled it, in case it was an ssl key error but that hasn’t worked…I’ve also cleared the browser cache but nothing gives
Add-on version: 0.15.0
You are running the latest version of this add-on.
System: Home Assistant OS 6.3 (aarch64 / raspberrypi4-64)
Home Assistant Core: 2021.9.4
Home Assistant Supervisor: 2021.09.0

** I have just seen there is an update 15.1 that addresses ssl protocols. I presume @frenck will be updating this in HomeAssistant shortly although I did notice this was updated back in May on Github.....Has this been overlooked ?

**Comment by gbfromhb** [comment]
I am also getting something close to this I think. I go to open the WebUI and I get:
xxxxxxxxxxxx.duckdns.org uses an unsupported protocol in Chrome
and get this 
ERR_SSL_VERSION_OR_CIPHER_MISMATCH this in Edge

Add-on version: 0.15.0

System: Home Assistant OS 6.3 (aarch64 / raspberrypi4-64)
Home Assistant Core: 2021.9.5
Home Assistant Supervisor: 2021.09.0

I also saw the 15.1 hope it will help. It has not made itself avaiiable to update in Home Assistant yet.

**Comment by mmatloka** [comment]
I have the same problem.

**Comment by maurizioandreotti60** [comment]
I'm geting the same issue, so I'm not alone.

**Comment by gbfromhb** [comment]
I still have this issue. Is there any guidance at all for this?Get Outlook for Android

**Comment by kierank01** [comment]
There is an update available to the duckdns addin, that has the following release note:

Add option to specify algorithm used for SSL certificates

Might help this issue, I'm also affected

**Comment by kierank01** [comment]
> There is an update available to the duckdns addin, that has the following release note:
> 
> Add option to specify algorithm used for SSL certificates
> 
> Might help this issue, I'm also affected

There is an extra config item required in duckdns (that is undocumented)...
algo: secp384r1

Not sure what algo can be set to, but secp384r1 noted on that git allows the adding to start, but does not resolve the tasmoadmin issue

**Comment by frenck** [comment]
Fixed on current dev.

**Comment by gbfromhb** [comment]
Thank you.
