### ISSUE TITLE
No 0.15.1 update with HA core-2021.10.0

### ISSUE THREAD

**Issue by gogreenpower** [hassio-addons/addon-tasmoadmin#207]
# Problem/Motivation

> Can't update to 0.15.1

## Expected behavior

> with 0,15,0 installed, I should see an update available

## Actual behavior

> Nothing

## Steps to reproduce

> Supervisor/Add-ons/nTasmoAdmin, no updates available

## Proposed changes

Must 0.15.1 be installed a different way?

**Comment by wokkeltje13** [comment]
same issue here

**Comment by brinzlee** [comment]
To be honest I am getting quite disallusioned with reporting problems in HA now. I know Frenk has been sick but there seems to be very few updates now from his side. And when there is a problem reported in github it is often closed with little or no description as to why. And if a description is provided it is often so technically explained only a programmer can fathom it out...

**Comment by ascillato** [comment]
Yes, it is compatible with Tasmota 10.

**Comment by NicciZar** [comment]
> Yes, it is compatible with Tasmota 10.

Thank you for your fast reply :)

**Comment by lebherz** [comment]
ok.. I add the Frenk Repro (not displayed in HA) 
https://github.com/hassio-addons/repository
now TasmotAdmin 0.15.1 appears:

![grafik](https://user-images.githubusercontent.com/11904931/140197514-6430fe55-5786-4115-afba-dc20d0c8b275.png)
![grafik](https://user-images.githubusercontent.com/11904931/140197542-d4cd8f36-6761-4647-a7d0-fae3326a5eb8.png)

and Tasmoadmin 0.15.1 appears again :)

**Comment by wokkeltje13** [comment]
For me that repo was already present, but no 0.15.1 visible.

**Comment by lebherz** [comment]
That is what I see "official add-on's":
![grafik](https://user-images.githubusercontent.com/11904931/140605465-74909c05-ec67-438e-90d0-fec8236d6a99.png)

and here @frenck 's repo 🎉:
![grafik](https://user-images.githubusercontent.com/11904931/140605473-5f1d5996-f761-49a8-982e-6c86e31be3d4.png)

**Comment by brinzlee** [comment]
Franks repo is not updated to 15.1

**Comment by lebherz** [comment]
jep, you are right! I had the problem, that I have'nt saw the TasmoAdmin in the "official add-ons" section. in the Community-section I can see and installed it... but 0.15.0 . My installed version, before I add the commnity-repo was 0.13.x 😖

**Comment by frenck** [comment]
TasmoAdmin never has been an core addon... so I think you are wrong there...

**Comment by frenck** [comment]
@brinzlee if you actually looked at things happening around here, you would have seen lots of process in replacing and updating things... but I can see your point of view. If you can't access it.. than I must have a "left it for dead" right?

**Comment by brinzlee** [comment]
@frenck thanks thats my kind of humour.....I've missed you

**Comment by frenck** [comment]
I don't think or received it as humor, for me you are just being a dick.

**Comment by brinzlee** [comment]
@frenck That's a very personal slur...And I take offence to that. Lighten up a little dude !!
You maintained the app and it hasn't been suported for a while. Where else do we get support from. The idea of this is to let people know...

**Comment by frenck** [comment]
Sure.

**Comment by brinzlee** [comment]
Thanks...Sorry you took it the wrong way....

**Comment by frenck** [comment]
I didn't think I took it the wrong way.

**Comment by brinzlee** [comment]
For goodness sake...Let it go......what bit don't you understand !!

**Comment by lebherz** [comment]
> 
> 
> TasmoAdmin never has been an core addon... so I think you are wrong there...

ok.. I don't remember how TasmoAdmin came on my HA Blue - sorry :)

**Comment by frenck** [comment]
Hehe don't worry :)

**Comment by NicciZar** [comment]
How comes that some people say they see version 0.15.1 and the others 0.15.0? I can only see that there is 0.15.0..

**Comment by frenck** [comment]
Because of an issue with the release scripts; for which I am rolling an update for. Please be patient, thanks.

**Comment by frenck** [comment]
A new version has been made available.

**Comment by gogreenpower** [comment]
Thank you for that, much appreciated
