### ISSUE TITLE
JSON Syntax Error 4:  Device not found

### ISSUE THREAD

**Issue by itcsburnett** [hassio-addons/addon-tasmoadmin#208]
# Problem/Motivation

Was unable to scan or manually add a SONOFF TH device with ext temp probe DS18B20 flashed with tasmo FW:
`{"deviceType":"Sonoff TH", "version":"2.0.5", "date":"May 23 2019 13:28:09", "mac":"b4e62d7fb2ab"}`

## Expected behavior

Entering the IP of the device, I expected it to be added

## Actual behavior

Recvd this error message:
`Device not found`

`JSON ERROR => 4: Syntax error
Please copy the whole error message and copy it in a new issue on GitHub. Somehow the Tasmota Firmware answered a wrong formatted JSON string which needs to get adjusted in TasmoAdmin.
JSON Answer => }`

## Steps to reproduce
Running TasmoAdmin version: 0.15.0

**Comment by frenck** [comment]
This is unfortunately a bug upstream that the add-on cannot do anything about.

Please report your issue with TasmoAdmin itself here: <https://github.com/reloxx13/TasmoAdmin>
