### ISSUE TITLE
ERR_SSL_VERSION_OR_CIPHER_MISMATCH

### ISSUE THREAD

**Issue by brinzlee** [hassio-addons/addon-tasmoadmin#209]
# Problem/Motivation
This has been fixed by the developer apparently with 15.1 but the addon store is not reflecting this update its only showing version 15.0. @frenck says its fixed in current dev but not sure what he means by this. Its not working for me until its updated
> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by rover1955** [comment]
I had the same issue.  I downloaded the ZIP file (CODE/Download ZIP), unzipped the file and copied the tasmoadmin folder to the addons share on my Hassos.  (If you have SAMBA addon installed you will have access to the addons share).  This share is for local addons not the Add-on Store addons.

Go to Supervisor and refresh and you should see Local Add-ons before Official Add-ons.  You can then install the Dev version. 

I kept theAdd-on Store version installed but turned off for now.  

The local version works and when the Add-on Store version upgrades, I can remove the local one.

Hope this helps.

**Comment by notovich** [comment]
fixed mine by removing SSL tick ✅  in Tasmoadmin 15.0 configuration and run UI in chrome 192.168.you.ip:9541 without "s" in http://

![image](https://user-images.githubusercontent.com/74376659/137640677-db1d47e7-7287-49c4-80fa-c36f78164e29.png)

**Comment by frenck** [comment]
This has been addressed in the latest version.
