### ISSUE TITLE
SSL doesn't work

### ISSUE THREAD

**Issue by andrewbpowers** [hassio-addons/addon-tasmoadmin#211]
# Problem/Motivation
I use Home Assistant over HTTPS(SSL) only.
But the SSK option in TasmoAdmin doesn't work.
The only way to use TamsoAdmin is over HTTP.

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
This has been fixed in the latest version
