### ISSUE TITLE
Automatically add to Home Assistant panel through ingress

### ISSUE THREAD

**Issue by felipecrs** [hassio-addons/addon-tasmoadmin#215]
It would be much simpler to configure, and we would not need to care about SSL certificates. Just like most of other add-ons.

**Comment by sinclairpaul** [comment]
As a suggestion, you may want to look through the previous issues logged about this.

How would you support firmware upgrades on the devices?

**Comment by felipecrs** [comment]
> As a suggestion, you may want to look through the previous issues logged about this.

You are absolutely right. Let me try to find here what is the limitation, one sec.

**Comment by felipecrs** [comment]
[Looks like someone already managed to make it work](https://github.com/hassio-addons/addon-tasmoadmin/pull/63), which means there isn't any technical limitation in it. However, it was not accepted due to @frenck's choice. He claims that some users would not like it to have it in the Home Assistant panel and, in such case, there would not be an option to disable.

This was the response from @ammmze though:

Sounds like an opportunity for improvement! If nothing else disable the ingress server in nginx though maybe hass.io may consider it as not having come up...idk. My point is that we're not at the end of the road. Things can (and should) change and be enhanced over time.

_Originally posted by @ammmze in https://github.com/hassio-addons/addon-tasmoadmin/issues/63#issuecomment-568072302_

Which is completely right. So, I'm going to find where such feature request would need to be opened, and open it. If it gets implemented, then there would be no excuse not to proceed with ingress in this add-on.

As a short term solution though, I would recommend you to pin one issue so that less people would create duplicates.

**Comment by felipecrs** [comment]
There one already, but with a slightly different situation: https://community.home-assistant.io/t/disabling-ingress/112491

There, the user accepted the solution as he only wanted to access outside ingress, and not disabling ingress itself.

**Comment by frenck** [comment]
You did my read my comments wrong. Tasmota devices communicate back (eg for firmware fetching) which doesn't work with ingress. Additional the TasmoAdmin project itself is more dead than alive.

For these two main reasons (as stated, declined and reviewed many times before) this will not be added or accepted.

**Comment by felipecrs** [comment]
Well, if you are talking about:

https://github.com/hassio-addons/addon-tasmoadmin/pull/63#discussion_r359230790

Then, it's simple: the port exposure should be kept active. And, if the URL path needs to match both in ingress and in the service itself, it can be accomplished by making the TasmoAdmin server to serve with the same path as the Home Assistant frontend would.

> Additional the TasmoAdmin project itself is more dead than alive.

Regarding this, I totally understand your point, especially considering that the `panel_iframe` approach works for most cases.

---

By the way, I see your name in every single place of Home Assistant. Congratulations for your engagement, I appreciate everything you are doing and certainly the community too. 👌
