### ISSUE TITLE
Update url not being passed properly

### ISSUE THREAD

**Issue by chuq00** [hassio-addons/addon-tasmoadmin#223]
# Problem/Motivation

> (Why the issue was filed)
The update url being sent to the devices has an extra http:// at the beginning of the url
## Expected behavior

> (What you expected to happen)
The correct URL to be passed to the devices and for then all to update
## Actual behavior

> (What actually happened)
An extra http://is pissed to the devices and they will not update. Also I noticed that it adds :95
## Steps to reproduce

> (How can someone else make/see it happen)
Go into the tasmoadmin on home assistant and update all devices then go to a device and look at url for update
## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it
Correct the code so it does not send the extra http:// when it updates the url on the device

**Comment by chuq00** [comment]
My Sonoff switches were on various different versions of tasmota from 8.1 to 9.5 the url that was sent to upgrade the devices was http://http://ota.tasmota.com/tasmota/release/tasmota.bin:9541/data/firmwares/tasmota.bin
I removed the first http:// and they still did not update. I had to remove the :9541data/firmwares/tasmota.bin then they did upgrade to 10.0 (minimal) now I am not sure if it is because I was not patient to see if it just was not done with completing the upgrade because when the switches would reboot they said that they were on minimal and for me to upgrade them, so I added the :9541/..    to the upgrade url and they all upgraded to 10.0 
So I'm not sure if there's a glitch in the code with adding the :9541/... Not allowing them to upgrade properly, but I would like to see the upgrade window to alert you to any devices running minimal, so you can make sure they get upgraded. Also, maybe a check if the device is still on the same version after it "completes upgrade successfully"

**Comment by Thunderbird2086** [comment]
I believe the fix will be released soon under https://github.com/reloxx13/TasmoAdmin/pull/447

**Comment by mvanlijden** [comment]
Not stale, still not able in released version in HA

**Comment by mvanlijden** [comment]
not stale, still no update

**Comment by XtraLarge** [comment]
Hi, i manually updates the "/var/www./tasmoadmin" directory with the actual code from the github repository. With this modification everything works great. 
Perhaps you can make a teamporary fix, because the official one takes such a long time.

**Comment by frenck** [comment]
We do not release from unstable.
