### ISSUE TITLE
ver 0.16.0 won't upload .bin.gz compressed Tasmota firmware files

### ISSUE THREAD

**Issue by mrneutron42** [hassio-addons/addon-tasmoadmin#224]
# Problem/Motivation

> I like to use the mass update feature for Tasmota OTA firmware updates.  Tasmota firmware has become too large to use the uncompressed .bin files, so there is a need to use the .bin.gz compressed firmware files.

## Expected behavior

> When using the Update Devices feature, I expected "Upload Successful" message when uploading the .bin.gz compressed firmware files.
![TasmoAdmin 0 16 0 success uploading bin firmware files](https://user-images.githubusercontent.com/70338169/145695330-7d83a77b-a28f-4619-9be8-6b44c69ca6f5.JPG)

## Actual behavior

> When using the Update Devices feature, I get "Upload Successful" message when uploading the .bin.gz compressed firmware files.
![TasmoAdmin 0 16 0 doesn't recognize bin gz firmware files](https://user-images.githubusercontent.com/70338169/145695332-905f836f-2088-4424-ac94-17d989bf0b0e.JPG)

## Steps to reproduce

> Open Update Devices window and add .bin.gz compressed firmware files to the file boxes and click NEXT.
![TasmoAdmin 0 16 0 uploading bin gz firmware files](https://user-images.githubusercontent.com/70338169/145695322-cecfdda3-79ac-42b8-b75e-fe7d78a8b7d5.JPG)

## Proposed changes

> Add support for .bin.gz compressed firmware files to TasmoAdmin.

**Comment by sinclairpaul** [comment]
The addon wraps the TasmoAdmin application, any feature requests would need to be logged upstream at https://github.com/reloxx13/TasmoAdmin

**Comment by mrneutron42** [comment]
Thanks for the pointer.  This docker stuff is confusing.
