### ISSUE TITLE
Show in Sidebar?!

### ISSUE THREAD

**Issue by Teuflor** [hassio-addons/addon-tasmoadmin#226]
Hey Franck,

is it possible thad you add the "show in Sidebar" feature to your addon?

in your shown screenshot it works, but in the live addon it dont.

greetings

**Comment by frenck** [comment]
See documentation: <https://github.com/hassio-addons/addon-tasmoadmin/blob/main/tasmoadmin/DOCS.md#embedding-into-home-assistant>
