### ISSUE TITLE
Add support for gzipped firmware binaries

### ISSUE THREAD

**Issue by byte4geek** [hassio-addons/addon-tasmoadmin#232]
Hi all,

is it possible to add the gizp support to tasmoadmin addon like the issue below?
https://github.com/reloxx13/TasmoAdmin/issues/403

**Comment by mvanlijden** [comment]
This is fixed with #231 
However I'm also still waiting for a new build to be released so the actual addon will also update :)

**Comment by mateuszdrab** [comment]
I think this is merged and available in the latest build.
![image](https://user-images.githubusercontent.com/26556541/159140476-e1d9de25-7135-4deb-9e7b-8dba29e9bd26.png)
