### ISSUE TITLE
Yet another ingress issue/solution?

### ISSUE THREAD

**Issue by mateuszdrab** [hassio-addons/addon-tasmoadmin#237]
# Problem/Motivation

I wanted to get ingress to work, the iframe solution didn't quite cut it for me due to aesthetics

## Proposed changes

Hey @frenck, I've seen the whole load of ingress issues so I decided to look into it myself and after a few hours I realized the solution is simpler than I thought. I got it to work, essentially. Screenshot as proof:

![image](https://user-images.githubusercontent.com/26556541/159276177-bba6da06-8c66-481f-925a-d9891d3b6603.png)

Achieving this required a few changes on the nginx config, one of which is already PRd (https://github.com/hassio-addons/addon-tasmoadmin/pull/236).
The changes allow for rewrite of the URLs on the fly.
The second change requires modification of the `top.php` (https://github.com/TasmoAdmin/TasmoAdmin/blob/master/tasmoadmin/includes/top.php) file to alter how the `$subdir` variable is set - it needs to be empty so that URIs built are relative. Tried setting the `TASMO_BASEURL` variable to `""` but it doesn't seem to work potentially because of the fact it's empty. Can potentially set it to `-` and the check and replace it during runtime.

Bonus point is that the web UI access can be completely disabled from the host, whilst an alternative HTTP port is exposed for firmware updates only.

This tool, whilst you said it's sort of dead, is still really useful and with a few tweaks, it will provide me an admin interface I need.

Question is, shall we PR this?

Once the PR is in, my next objective would be to make firmware updates work without changing the OTA url on the tasmota device, followed by staggered upgrades. I have 40 devices here at home, updating them is risky all at once IMHO.

Thanks

**Comment by osyrixx** [comment]
Please @mateuszdrab, could you PR this that ingress is added within the next version or describe how you got ingress to work? Thanks alot.
