### ISSUE TITLE
recover password

### ISSUE THREAD

**Issue by kegaul1** [hassio-addons/addon-tasmoadmin#239]
# Problem/Motivation
method for recovering a forgotten password?

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by SM-26** [comment]
This add-on doesn't have any password recovery options.
see https://github.com/hassio-addons/addon-tasmoadmin/issues/77#issuecomment-612848578=
You need to reinstall the add-on.


FYI, you will lose all of the data, so take this into account.
