### ISSUE TITLE
No TasmoAdmin anymore

### ISSUE THREAD

**Issue by antoinevandenhurk** [hassio-addons/addon-tasmoadmin#24]
# TasmoAdmin doesn't work anymore

> TasmoAdmin doesn't work anymore,I can't find a way to solve it
> Underneath is the loggin when I start the Addon

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-tasmoadmin: applying... 
[fix-attrs.d] 01-tasmoadmin: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Hass.io Add-on: TasmoAdmin v0.5.1
 Centrally manage all your Sonoff-Tasmota devices
 From: Community Hass.io Add-ons
 By: Franck Nijhof <frenck@addons.community>
-----------------------------------------------------------
 armhf / Resin OS 2.3.0+rev1 / HA 0.76.2 / SU 127 / stable
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to INFO
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] 02-updates.sh: executing... 
INFO: You are running the latest version of this add-on
[cont-init.d] 02-updates.sh: exited 0.
[cont-init.d] 10-requirements.sh: executing... 
```

**Comment by frenck** [comment]
@antoinevandenhurk Sorry to hear you are having problems.

This is not the complete log. Could you provide it? Thanks!

**Comment by antoinevandenhurk** [comment]
Underneath the log, when I start the Hassio Addon. Afterwards the green bulb turns back to grey.

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-tasmoadmin: applying... 
[fix-attrs.d] 01-tasmoadmin: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Hass.io Add-on: TasmoAdmin v0.5.1
 Centrally manage all your Sonoff-Tasmota devices
 From: Community Hass.io Add-ons
 By: Franck Nijhof <frenck@addons.community>
-----------------------------------------------------------
 armhf / Resin OS 2.3.0+rev1 / HA 0.76.2 / SU 127 / stable
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to INFO
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] 02-updates.sh: executing... 
INFO: You are running the latest version of this add-on
[cont-init.d] 02-updates.sh: exited 0.
[cont-init.d] 10-requirements.sh: executing... 
FATAL: The configured certfile is not found
[cont-init.d] 10-requirements.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.
 
 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
s6-nuke: fatal: unable to kill: No such process

**Comment by frenck** [comment]
This is the error:

`FATAL: The configured certfile is not found`

You have SSL enabled and the add-on is not able to find the SSL certificated needed for this.
This is not a add-on issue, but a user configuration issue.

**Comment by antoinevandenhurk** [comment]
You're right, this was very helpfull
