### ISSUE TITLE
Fatal error: Uncaught Error: Undefined constant self::USER_CONFIG_CONFIG_GZIP_PACKAGE

### ISSUE THREAD

**Issue by maramazza** [hassio-addons/addon-tasmoadmin#242]
Hi
into the setup page with the 0.18 version i have a fatal error
What can i do to remove it?
Thanks
<img width="1172" alt="Screenshot 2022-06-10 at 09 15 49" src="https://user-images.githubusercontent.com/209152/173011458-997f8ef1-2005-4885-9d70-e703455fc18b.png">

**Comment by Pawel128** [comment]
Hello, it's the same for me:
------
Home Assistant Core 2022.6.4
Home Assistant Supervisor 2022.05.3
Home Assistant OS 8.1
rpi4-64
-----
Fatal error: Uncaught Error: Undefined constant self::USER_CONFIG_CONFIG_GZIP_PACKAGE in /var/www/tasmoadmin/tasmoadmin/tmp/cache/i18n/php_i18n_76458863c223cc0c347157b00f58477a___L_pl.cache.php:407 Stack trace: #0 /var/www/tasmoadmin/tasmoadmin/tmp/cache/i18n/php_i18n_76458863c223cc0c347157b00f58477a___L_pl.cache.php(407): constant() #1 /var/www/tasmoadmin/tasmoadmin/includes/top.php(143): __L::__callStatic() #2 /var/www/tasmoadmin/tasmoadmin/pages/site_config.php(296): __() #3 /var/www/tasmoadmin/tasmoadmin/index.php(55): include_once('...') #4 {main} thrown in /var/www/tasmoadmin/tasmoadmin/tmp/cache/i18n/php_i18n_76458863c223cc0c347157b00f58477a___L_pl.cache.php on line 407

**Comment by charettepa** [comment]
I am also seeing this issue with devices page spinning endlessly with fatal error

Home Assistant Core 2022.6.4
Home Assistant Supervisor 2022.05.3
Home Assistant OS 8.1
Odroid(HA-Blue)

**Comment by pjbpaul** [comment]
I'm not getting any log errors but I am getting the spinners as in the pic above.

Home Assistant Core 2022.6.4
Home Assistant Supervisor 2022.05.3
Home Assistant OS 8.1

On a vMware virtual machine

**Comment by booroondookZ** [comment]
It's the same for me too.

**Comment by onlize** [comment]
I have the same spinning. When I go to Devices, Update, and click on the Automatic button, it shows everything how it should be, but not on the Devices, List page.

**Comment by MightyWomble2020** [comment]
Same for me with spinning progress wheels. Downgrade to previous version solves the issue for me.

**Comment by big-ted** [comment]
same issue, downgraded and working

**Comment by booroondookZ** [comment]
> same issue, downgraded and working

How to install the older version of this add-on?

**Comment by big-ted** [comment]
> > same issue, downgraded and working
> 
> How to install the older version of this add-on?

Restored just the addon from my last full snapshot

**Comment by sagitt** [comment]
same here

**Comment by essegi65** [comment]
same here

**Comment by frenck** [comment]
I don't need  more "Same here" comments; those are rarely helpful. Instead, just add a 👍 to the issue.

**Comment by frenck** [comment]
Fixed in #243 

![image](https://user-images.githubusercontent.com/195327/173246592-7186520e-4cc6-4fa1-96cd-2f3e6e4fa709.png)
