### ISSUE TITLE
could not read MyConfig.json

### ISSUE THREAD

**Issue by Kedryn** [hassio-addons/addon-tasmoadmin#25]
# Problem/Motivation

TasmoAdmin doesnt work anymore

## Expected behavior

Open the web page, but it des not

## Actual behavior

returns a  "could not read MyConfig.json"

## Steps to reproduce

Almost everytime i restart the docker image in hassio, it boots. When i open the UI i get only a "could not read MyConfig.json"

## Proposed changes

Nope, tried removing it from hassio e reinstalling, but it alwasy (almost) gives the same error. Some times it works, but very slowly.

**Comment by frenck** [comment]
Please report this issue to the upstream project: https://github.com/reloxx13/TasmoAdmin
This is not related to add-on, but a result of the way they store their configurations.
