### ISSUE TITLE
Can't decode payload

### ISSUE THREAD

**Issue by dingausmwald** [hassio-addons/addon-tasmoadmin#252]
When tasmoadmin is running and list tab is opened (detailed view) i get this in HA logs spammed:

`Can't decode payload b'{"StatusSTS":{"Time":"2022-07-16T12:51:04","Uptime":"0T16:01:58","UptimeSec":57718,"Heap":20,"SleepMode":"Dynamic","Sleep":10,"LoadAvg":99,"MqttCount":95,"POWER1":"ON","Channel1":100,"POWER2":"ON","Channel2":83,"POWER3":"ON","Channel3":83,"Color":"FFD3D3","Wifi":{"AP":1,"SSId":"LEDE 2,4ghz","BSSId":"28:D1:27:4D:EB:48","Channel":3,"Mode":"11n","RSSI":48,"Signal":-76,"LinkCount":1,"Dow0\x85\x03\x00\x1astat/tasmota_1A39' on stat/tasmota_1A3963/STATUS11 with encoding utf-8 (for <Job HassJobType.Callback <function TasmotaStatusSensor.subscribe_topics.<locals>.state_message_received at 0x7f98f84160>>)
`
newest tasmotaadmin,
newest HA core

**Comment by inverse** [comment]
Sounds like more an issue for https://github.com/home-assistant/core

This error is coming from the Tamota integration not tasmoadmin.

**Comment by dingausmwald** [comment]
allright, ill post it there
