### ISSUE TITLE
Page /upload_form issuse

### ISSUE THREAD

**Issue by kfulko** [hassio-addons/addon-tasmoadmin#254]
# Problem/Motivation

> Error when click a upload_form page to update Tasmota devices

## Expected behavior

 :)

## Actual behavior

> Actual error on page:
Fatal error: Uncaught GuzzleHttp\Exception\ConnectException: cURL error 28: SSL connection timeout (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://raw.githubusercontent.com/arendst/Tasmota/development/RELEASENOTES.md?r=1662312596 in /var/www/tasmoadmin/tasmoadmin/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:210 Stack trace: #0 /var/www/tasmoadmin/tasmoadmin/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(158): GuzzleHttp\Handler\CurlFactory::createRejection() #1 /var/www/tasmoadmin/tasmoadmin/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(110): GuzzleHttp\Handler\CurlFactory::finishError() #2 /var/www/tasmoadmin/tasmoadmin/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(47): GuzzleHttp\Handler\CurlFactory::finish() #3 /var/www/tasmoadmin/tasmoadmin/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__invoke() #4 /var/www/tasmoadmin/tasmoadmin/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(48): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}() #5 /var/www/tasmoadmin/tasmoadmin/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(35): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}() #6 /var/www/tasmoadmin/tasmoadmin/vendor/guzzlehttp/guzzle/src/Middleware.php(31): GuzzleHttp\PrepareBodyMiddleware->__invoke() #7 /var/www/tasmoadmin/tasmoadmin/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(71): GuzzleHttp\Middleware::GuzzleHttp\{closure}() #8 /var/www/tasmoadmin/tasmoadmin/vendor/guzzlehttp/guzzle/src/Middleware.php(63): GuzzleHttp\RedirectMiddleware->__invoke() #9 /var/www/tasmoadmin/tasmoadmin/vendor/guzzlehttp/guzzle/src/HandlerStack.php(75): GuzzleHttp\Middleware::GuzzleHttp\{closure}() #10 /var/www/tasmoadmin/tasmoadmin/vendor/guzzlehttp/guzzle/src/Client.php(331): GuzzleHttp\HandlerStack->__invoke() #11 /var/www/tasmoadmin/tasmoadmin/vendor/guzzlehttp/guzzle/src/Client.php(168): GuzzleHttp\Client->transfer() #12 /var/www/tasmoadmin/tasmoadmin/vendor/guzzlehttp/guzzle/src/Client.php(187): GuzzleHttp\Client->requestAsync() #13 /var/www/tasmoadmin/tasmoadmin/vendor/guzzlehttp/guzzle/src/ClientTrait.php(44): GuzzleHttp\Client->request() #14 /var/www/tasmoadmin/tasmoadmin/src/Helper/TasmotaHelper.php(26): GuzzleHttp\Client->get() #15 /var/www/tasmoadmin/tasmoadmin/pages/upload_form.php(7): TasmoAdmin\Helper\TasmotaHelper->getReleaseNotes() #16 /var/www/tasmoadmin/tasmoadmin/index.php(55): include_once('...') #17 {main} thrown in /var/www/tasmoadmin/tasmoadmin/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 210

Addon version: 2.00
Home Assistant Version: 2022.08.3
Supervisor Version: 2022.08.5

Another webpage on this addon works, addon have many restart, addon don't have any errors on log page.
![screenshot-192 168 2 118_9541-2022 09 04-19_44_47](https://user-images.githubusercontent.com/3510639/188326615-5c21c16d-6fc8-45e8-8698-391b9cbeddc4.png)

**Comment by inverse** [comment]
Please raise this issue upstream on https://github.com/TasmoAdmin/TasmoAdmin

Looks like we're not gracefully catching timeouts when fetching the release notes.

**Comment by kfulko** [comment]
Ok :) Close here.
