### ISSUE TITLE
Fatal error: Allowed memory size exhausted during AutoScan

### ISSUE THREAD

**Issue by llluis** [hassio-addons/addon-tasmoadmin#255]
# Problem/Motivation

Can't autoscan my network, it fails with an out of memory error.

## Expected behavior

Select the IP range from 192.168.1.1 to 192.168.1.254 and have all devices discovered.

## Actual behavior

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /var/www/tasmoadmin/tasmoadmin/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 149

Having less IPs and the range eventually works, but with very small segments.

## Steps to reproduce

Install standard configuration.
Open the interface and select autoscan.
Select range from 1 to 254
(I have about 30 devices to be discovered using DHCP, so they are all over the range. Running on a Raspi 4 HassOS).

## Proposed changes

I can do multiple AutoScans with small ranges or reduce my DHCP range, but, it doesn't change the fact the application has a limitation.

**Comment by inverse** [comment]
I'm unable to reproduce the issue both on PI4 or in the dev env.

Are you able to provide the full stack trace to figure out what path is causing the issue?

**Comment by llluis** [comment]
I should have thought of that (posting the full stack), sorry! Lesson learned for the next.

I have good news and bad news... 
I found the issue and it was user error: a typo in the range. Instead of, for instance, 192.168.1.1 to 192.168.1.254, it was 192.168.1.1 to 192.168.11.254. Sorry for wasted time.

On the other hand, you can still crash the app if your range is too big or spans accross multiple subnets. Is this even supported?

**Comment by inverse** [comment]
Input validation is def something that should be handled - could you create an issue with these details in the upstream repo https://github.com/TasmoAdmin/TasmoAdmin
