### ISSUE TITLE
TasmoAdmin v2.2.0 available

### ISSUE THREAD

**Issue by StayPirate** [hassio-addons/addon-tasmoadmin#267]
[TasmoAdmin `v2.2.0`](https://github.com/TasmoAdmin/TasmoAdmin/releases/tag/v2.2.0) was released the 6th of the current month. Could you please update this add-on?

**Comment by frenck** [comment]
This is a request, not an issue report.
Add-ons are update regularly, no issue creation is needed for that.

Closing this issue for that reason.

../Frenck
