### ISSUE TITLE
Upgrade to tasmoadmin 1.6.0

### ISSUE THREAD

**Issue by tjorim** [hassio-addons/addon-tasmoadmin#27]
# Problem/Motivation

Tasmoadmin 1.6.0 is in the works, this is a short list with things that can/should/need to be done in the next release of this add-on. 

- [ ] new option for http/https: https://github.com/reloxx13/TasmoAdmin/commit/7be2b6816995c19042e265bcfaebae8942bed2e5

- [ ] latest release uses self-signed ssl (like the unifi add-on, but maybe just stick to the existing option): https://github.com/reloxx13/TasmoAdmin/commit/b557965312b5b74f95c7990391296eae3d90074b

- [ ] this update needs a migration: https://github.com/reloxx13/TasmoAdmin/commit/ade5b9b440050c902b75244765297915b2061a60, https://github.com/reloxx13/TasmoAdmin/commit/9d57a3db76b0d69ccd5b96d56528014485836453...

**Comment by vrtclhykr** [comment]
How do we update on Hassio RP3?  I cannot get version 0.5.1 to work anymore.  Tried uninstall, reinstall couple times.  Regards, Vrt
