### ISSUE TITLE
Updating Tasmota devices is not working

### ISSUE THREAD

**Issue by rickgartner** [hassio-addons/addon-tasmoadmin#272]
# Problem/Motivation
Unable to connect to this location to download updates.  It appears the data path is hard coded in the app.

Full Firmware is not accessible on the server at https://172.30.33.1:9541/data/firmwares/tasmota.bin.gz
Please check the OTA IP address and port are correct

I am able to change the IP and port, but data/firmwares seem to be hard coded and cannot be changed.

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by inverse** [comment]
The path shouldn't matter as it's what's served up from from the addon.

By default the addon resolves the host IP for the OTA server URL which in this instance is one from within the docker network.

You should change this to be the IP of the device running Home Assistant and it should work.

**Comment by sinclairpaul** [comment]
You will also want to remove SSL from your config to use it as an OTA update, ESP's don't have enough room to hold the cert chains from what I recall

**Comment by rickgartner** [comment]
That works!  Pointed to my instance of HA and disabled SSL from the TasmoAdmin config in HA and within
TasmoAdmin
Thanks for your help.
