### ISSUE TITLE
Container always reporting as unhealthy when SSL is enabled

### ISSUE THREAD

**Issue by ScottG489** [hassio-addons/addon-tasmoadmin#273]
# Problem/Motivation

Docker is reporting the container as unhealthy all the time and the supervisor is as well (logs from supervisor):
```
[supervisor.addons.addon] Watchdog found addon TasmoAdmin is unhealthy, restarting...
```
Then it will restart it. This will cycle once every ~1.5 mins.

## Expected behavior

`docker ps` to report the container as `healthy`

## Actual behavior

`docker ps` reports the container as `unhealthy`

## Steps to reproduce

Install the addon and run it with `ssl: true` in the configuration

## Proposed changes

I see healthchecks were added recently in #270 which I assume is when this problem would have started. Looking at [other `HEALTHCHECKS` in this organization](https://github.com/search?q=org%3Ahassio-addons+HEALTHCHECK+language%3ADockerfile&type=code&l=Dockerfile) nothing sticks out.

I run Node-Red and AdGuard as well with SSL and they have similar `HEALTHCHECK` commands. UniFi has a slightly different command though: https://github.com/hassio-addons/addon-unifi/commit/57698f03ebae059031113df51f4341d4f7f19fc7

I'm also running it on port `9541` (default) if that matters.

What are your thoughts?

**Comment by hostirosti** [comment]
I ran into the same issue. It appears to be that the healthcheck is configured to work without SSL only https://github.com/hassio-addons/addon-tasmoadmin/blob/056146b25d10d9ab9f4d57357b7c31269c04c8a7/tasmoadmin/Dockerfile#L60

For SSL enabled it should be:
```
curl --fail --insecure https://127.0.0.1:9541
```
