### ISSUE TITLE
Document HTTP API requirement, and CURL error(s)

### ISSUE THREAD

**Issue by don-willingham** [hassio-addons/addon-tasmoadmin#275]
# Problem/Motivation

> When attempting to add a device with HTTP API disabled, results in an error:
```
Device not found

CURL ERROR => cURL error 52: Empty reply from server (see
https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://192.168.1.234/cm?
user=admin&password=********&cmnd=status+0
```

## Expected behavior

> Error could be more clear, or [DOCS.md](https://github.com/hassio-addons/addon-tasmoadmin/blob/main/tasmoadmin/DOCS.md) could include something like "Tasmota devices must enable HTTP API. Either by checking HTTP API enable on the Configure Other page, or entering `SetOption128 1` in the console."

## Actual behavior

> I followed https://curl.haxx.se/libcurl/c/libcurl-errors.html and 52 reads:
```
CURLE_GOT_NOTHING (52)

Nothing was returned from the server, and under the circumstances, getting nothing is considered an error.
```

## Steps to reproduce

> Remove tasmota device if it is already added. Disable HTTP API. Attempt to add tasmota device again.

## Proposed changes

> Include something like "Tasmota devices must enable HTTP API. Either by checking HTTP API enable on the Configure Other page, or entering `SetOption128 1` in the console." in [DOCS.md](https://github.com/hassio-addons/addon-tasmoadmin/blob/main/tasmoadmin/DOCS.md). The error codes could be decoded locally instead of referring the user to another site. Some users may use tasmota because it doesn't require internet access.

**Comment by don-willingham** [comment]
I was about to PR https://github.com/don-willingham/addon-tasmoadmin/tree/doc_req_http_api, but https://github.com/hassio-addons/addon-tasmoadmin/blob/main/.github/CONTRIBUTING.md#contributing suggests creating an issue first. The next section contradicts that with "Even better: You could submit a pull request with a fix / new feature!".

**Comment by don-willingham** [comment]
Actually, it looks like this just wraps https://github.com/tasmoadmin/tasmoadmin for integration within HomeAssistant. Updates for error messages would have to happen there. I arrived here, as http://192.168.1.XX:8123/hassio/addon/a0d7b954_sonweb/info pointed me to https://github.com/hassio-addons/addon-tasmoadmin

**Comment by inverse** [comment]
`DOCS.md` I would say is more specific to this addon - I'd say create a PR upstream in https://github.com/TasmoAdmin/TasmoAdmin
