### ISSUE TITLE
Show in sidebar option

### ISSUE THREAD

**Issue by JampireX** [hassio-addons/addon-tasmoadmin#283]
It's will be good to see native ingress "show in sidebar" option like other popular addons like NodeRed or AdGuardHome have. 
I know about embedding by "panel_iframe" option, but with this way i can't access TasmoAdmin when connected to HASS remotely. (cause TasmoAdmin link is local)

![image](https://user-images.githubusercontent.com/24954035/222717512-5b69b815-4369-4f2e-ae80-72f384952b66.png)

**Comment by frenck** [comment]
Yup, discussed many times before, and documented it isn't there and will not be added any time soon (technical limitations).

../Frenck
