### ISSUE TITLE
PHP Problem

### ISSUE THREAD

**Issue by detafun** [hassio-addons/addon-tasmoadmin#285]
Hallo,
ich habe gerade wie gewohnt die neue Version V3 installiert.
Nun habe ich beim aufruf folgendes:
`Fatal error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.1.0". You are running 7.4.33. in /var/www/html/tasmoadmin/vendor/composer/platform_check.php on line 24`

Aber bei mir ist 
`rock@rock:~$ php -v
PHP 8.1.16 (cli) (built: Feb 14 2023 18:28:06) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.16, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.16, Copyright (c), by Zend Technologies
rock@rock:~$ 
`
Installiert. Linux Betriebsystem

**Comment by frenck** [comment]
I think you meant to report an issue with the TasmoAdmin project. This is an Home Assistant add-on, so you are in the wrong place.

../Frenck
