### ISSUE TITLE
panel_iframe won't past login page

### ISSUE THREAD

**Issue by platini76** [hassio-addons/addon-tasmoadmin#286]
my config:
panel_iframe:
  tasmoadmin:
    title: TasmoAdmin
    icon: mdi:lightbulb-on
    url: http://192.168.0.50:9541

system won't login... any suggestions?
thanks

**Comment by inverse** [comment]
https://github.com/hassio-addons/addon-tasmoadmin/issues/125#issuecomment-776799104

This answer will probably help.

**Comment by platini76** [comment]
my HA access is a name xxxxx.duckdns.org
I dont' want to open another port 9541 on the router and I want simply to access to my page http://192.168.0.50:9541/
how to do it?
