### ISSUE TITLE
Unable to OTA devices, latest HA, latest Tasmoadmin, HAOS install.

### ISSUE THREAD

**Issue by mattlward** [hassio-addons/addon-tasmoadmin#291]
# Problem/Motivation
Cannot OTA my devices, appears that the files are never download to my HA server.

> (Why the issue was filed)
Because I have several devices I like to keep current.
## Expected behavior
I would expect the OTA to work, it does work from the devices looking to github for the firmware.
> (What you expected to happen)

## Actual behavior

> (What actually happened)
The Tasmoadmin addon reports the error "Full Firmware is not accessible on the server at http://192.168.1.6:9541/data/firmwares/tasmota.bin.gz
Please check the OTA IP address and port are correct " regardless of config.
## Steps to reproduce
When filling out the update form and either picking automatic or supplying my own files via browse I end up in the same situation.

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)
I do not know how to fix it.
![TA1](https://user-images.githubusercontent.com/8540074/227652004-421308e6-93f7-4a1b-922c-40f1157bcc73.jpg)
![TA2](https://user-images.githubusercontent.com/8540074/227652013-1289b47d-b533-4cc0-9d48-c74586b5040f.jpg)
![TA3](https://user-images.githubusercontent.com/8540074/227652163-6952d027-a841-44b5-9c52-6183a8138b57.jpg)

**Comment by inverse** [comment]
The check that's being done is the backend is checking if it can access the firmware that the given URL to ensure that things are downloaded/accessible.

I'm guessing the firmware is not accessible on the URL provided?

**Comment by quadcom** [comment]
This was posted a few days ago. I am seeing the same problem.

https://github.com/TasmoAdmin/TasmoAdmin/issues/810

**Comment by mattlward** [comment]
I still have not been able to get this working... 
With BE and FE checks disabled, I get the following...
![image](https://github.com/hassio-addons/addon-tasmoadmin/assets/8540074/5a3ded1c-f3c3-458c-a0b4-530ba6e3afd6)

Looks good, that is the version I would expect.  When I attempt and upgrade I get the following log...
![image](https://github.com/hassio-addons/addon-tasmoadmin/assets/8540074/0f445cc5-bc36-40d6-9705-96500b42867b)

I have been unable to find the downloaded file on my HA machine...  If I try the OTA URL in my browser I am greeted with a 403.

**Comment by mattlward** [comment]
Ok, so I installed TasmoAdmin on my Unraid server as a docker container and it will OTA properly.  I can run it there, but I really want my HA server to handle all the duties of my automated home.  I have updated everything including the latest TasmoAdmin and the latest version of HA.  

This stinks of TasmoAdmin not having correct file system permissions in HA.

**Comment by aumuelle** [comment]
i'm seeing the very same problems on my side.

"Minimal Firmware is not accessible on the server at http://10.0.0.126:9541/data/firmwares/tasmota-minimal.bin.gz
Please check the OTA IP address and port are correct
Full Firmware is not accessible on the server at http://10.0.0.126:9541/data/firmwares/tasmota.bin.gz
Please check the OTA IP address and port are correct"

wget http://10.0.0.126:9541/data/firmwares/tasmota-minimal.bin.gz
--2023-05-26 09:06:30--  http://10.0.0.126:9541/data/firmwares/tasmota-minimal.bin.gz
Connecting to 10.0.0.126:9541... connected.
HTTP request sent, awaiting response... 403 Forbidden
2023-05-26 09:06:30 ERROR 403: Forbidden.

logs are not very usefull..... (seems that only the startup of the module gets logged)


is this update-service working for anybody???

**Comment by inverse** [comment]
Very strange - I'm running the addon from the edge repository and not experiencing any issues.

```
malachi@pulsar ~ $ curl -I http://192.168.1.100:9541/data/firmwares/tasmota-minimal.bin.gz
HTTP/1.1 200 OK
Server: nginx/1.24.0
Date: Fri, 26 May 2023 21:06:27 GMT
Content-Type: application/octet-stream
Content-Length: 265930
Last-Modified: Fri, 26 May 2023 21:05:57 GMT
Connection: keep-alive
ETag: "64711f35-40eca"
Access-Control-Allow-Origin: *
Accept-Ranges: bytes

malachi@pulsar ~ $ curl -I http://192.168.1.100:9541/data/firmwares/tasmota.bin.gz
HTTP/1.1 200 OK
Server: nginx/1.24.0
Date: Fri, 26 May 2023 21:06:37 GMT
Content-Type: application/octet-stream
Content-Length: 453911
Last-Modified: Fri, 26 May 2023 21:05:57 GMT
Connection: keep-alive
ETag: "64711f35-6ed17"
Access-Control-Allow-Origin: *
Accept-Ranges: bytes
```

**Comment by aumuelle** [comment]
well, this is sort of strange.... but something trivial as **deinstalling and reinstalling the addon** did solve the problems in my case.
if you have not done so allready,  you could give it a try....



_Device 5
[2023-06-24T20:28:11.061Z] Starte Update Prozess
[2023-06-24T20:28:11.061Z] Attempting upgrade to version 12.5.0
[2023-06-24T20:28:11.061Z] Checking version...
[2023-06-24T20:28:11.201Z] Current version is 12.1.1(tasmota)
[2023-06-24T20:28:11.201Z] OTA Url => http://10.0.0.126:9541/data/firmwares/tasmota.bin.gz
[2023-06-24T20:28:11.286Z] Starte Module update...
[2023-06-24T20:28:11.367Z] Sleeping for 10s...
[2023-06-24T20:28:21.368Z] Update gestartet
[2023-06-24T20:28:21.368Z] Checking version...
[2023-06-24T20:28:21.424Z] Failed to fetch trying again... attempts left 9 sleeping for 10s...
[2023-06-24T20:28:31.426Z] Checking version...
...
[2023-06-24T20:29:46.534Z] Version is 12.5.0(tasmota)
[2023-06-24T20:29:46.534Z] Device upgrade successful_

**Comment by mjkl-gh** [comment]
For me I had SSL enabled on the addon, which blocks the `http://` and opens it on `https://`
![image](https://github.com/hassio-addons/addon-tasmoadmin/assets/9350991/aa022435-4251-4f69-87d1-394b8736bb1b)

If i `wget https://<my_domainname_or_IP>:9541/data/firmwares/tasmota-sensors.bin.gz --no-check-certificate` I could download it

disabling ssl on the HA addon fixes it
