### ISSUE TITLE
Alternate nightmode colors?

### ISSUE THREAD

**Issue by MaxVonEvil** [hassio-addons/addon-tasmoadmin#297]
# Problem/Motivation

Hi, would it be possible to use some alternate colors, as it seems it's only the background white which changes

## Expected behavior

Some lighter colors for the switches etc and lighter text would improve readability

## Actual behavior

The current colorscheme, does not work well for nightmode:

![image](https://user-images.githubusercontent.com/19863636/227796605-1b1af003-0734-40e7-80c5-e2ee8e0bfb69.png)

## Proposed changes

Have a look at the color themes for Zigbee2MQTT and ZwaveJS2MQTT below for inspiration

![image](https://user-images.githubusercontent.com/19863636/227796433-7651775e-dc0e-45ee-bd8b-801ba689c5ba.png)

![image](https://user-images.githubusercontent.com/19863636/227796512-cfd11d02-f8be-4c56-b1e9-e9ce0d961b45.png)

Thank you!

**Comment by frenck** [comment]
Hi there @MaxVonEvil 👋 

That is really a feature request for the TasmoAdmin project itself, this is the TasmoAdmin Add-on project, which wraps that.

If the upstream project adds this feature, it will end up into the add-on as well.

../Frenck
