### ISSUE TITLE
Rename SonWEB to TasmoAdmin

### ISSUE THREAD

**Issue by RaymondMouthaan** [hassio-addons/addon-tasmoadmin#3]
Hai @frenck 

SonWeb has been renamed to TasmoAdmin. 
Also the SelfUpdate feature is going to be disabled a little different from your proposal (see https://github.com/reloxx13/TasmoAdmin/issues/105)

Also new releases will be pushed to https://github.com/reloxx13/TasmoAdmin/releases where .tar.gz or .zip can be used to update the hassio addon.

Greets,
Ray

**Comment by frenck** [comment]
Thanks for creating the ticket @RaymondMouthaan!
I've already made the base changes yesterday. Will do finished asap.

**Comment by gnkarn** [comment]
Question:  in my case almost all devices have custom configs , 
is it possible to link the devices to our own individual device repo either local git or on github ?

**Comment by frenck** [comment]
@gnkarn Please stay on topic in issues on GitHub.
For support questions, please use the Community Forums. This add-on has a dedicated topic on the forums.

**Comment by frenck** [comment]
The renaming has been done, `v0.2.0` of the add-on has been released.
