### ISSUE TITLE
Container unhealthy: "sh: ]: unknown operand"

### ISSUE THREAD

**Issue by IntExCZ** [hassio-addons/addon-tasmoadmin#300]
# Problem/Motivation

When checking container status via Portainer, health status reports "unhealthy".

## Expected behavior

Container healthy

## Actual behavior

Container unhealthy, Last output: "sh: ]: unknown operand"

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

Probably problem in "HEALTHCHECK CMD"

**Comment by sinclairpaul** [comment]
Probably need some more details here, the healthcheck works fine, so why is this an issue in a third party app?

**Comment by IntExCZ** [comment]
![image](https://user-images.githubusercontent.com/55029847/228701751-bc549d9c-cbb4-4d98-a1a6-ae0922e8b352.png)
Not third party app, HA.

**Comment by IntExCZ** [comment]
Full view...
![image](https://user-images.githubusercontent.com/55029847/228701925-8f5ee6c7-b553-4bfa-a204-db5a7c76d8e3.png)

**Comment by sinclairpaul** [comment]
Portainer is a third party app, the healthcheck command is at <https://github.com/hassio-addons/addon-tasmoadmin/blob/4a2e8dc25b6dce61523d111721c4dedd4aa7fa18/tasmoadmin/Dockerfile#L61> not sure what the expected outcome is here.

**Comment by IntExCZ** [comment]
Yes, but it just resoprts Docker container status, not own status.

**Comment by sinclairpaul** [comment]
Would suggest you investigate this with the app itself, the healthcheck is valid and works.

**Comment by IntExCZ** [comment]
Nope, it is not.
I reinstalled the addon (without any configuration, just clean) and it reports the unhealth status.
![image](https://user-images.githubusercontent.com/55029847/228702672-c1365a0c-8849-48b0-aee1-1d3c011c64df.png)
