### ISSUE TITLE
FeatureRequest: use ingress

### ISSUE THREAD

**Issue by ottes** [hassio-addons/addon-tasmoadmin#303]
# Problem/Motivation

Most of the AddOns use an inrgess, my problem is, that my hass instance is public reachable and so are all addons, that use ingress. If i want to have a look at tasmo-admin UI, i would have  to be at home or make this public too.

https://developers.home-assistant.io/docs/add-ons/presentation/#ingress

## Expected behavior

have TasmoAdmin in Sidebar, not as iframe, but as ingres

**Comment by frenck** [comment]
Please... use search and such and save yourself the effort of creating an issue. Additionally, this is not an issue, but a feature request.

Closing.
