### ISSUE TITLE
cannot use DNS names

### ISSUE THREAD

**Issue by vajonam** [hassio-addons/addon-tasmoadmin#31]
# Problem/Motivation

I cannot specify dns names for my Tasmota devices on my network

## Expected behavior

Should be able to use dns or ip address to search for tasmota devices

## Actual behavior

can only use IP address

## Steps to reproduce

search for a device with dns names, also tried searching from just the container. 

```
$ docker exec -it addon_somehex_sonweb /bin/bash
root@a0d7b954-sonweb:/$ nslookup google.com
nslookup: can't resolve '(null)': Name does not resolve

nslookup: can't resolve 'google.com': Try again
root@a0d7b954-sonweb:/$ nslookup nodemcu_01
nslookup: can't resolve '(null)': Name does not resolve

nslookup: can't resolve 'nodemcu_01': Try again
root@a0d7b954-sonweb:/$ 
```

## Proposed changes

add the ability to specify dns names by either mapping /etc/resolv.conf from the dns hosts or provide it the config.json as section to specify dns

**Comment by frenck** [comment]
Please provide the add-on logs.

**Comment by vajonam** [comment]
Not sure you can see anything from the logs this a name resolution issue. nodemcu_02 resolves fine by the way on my network. 


Here is an image.

https://imgur.com/a/doQ2haA

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-tasmoadmin: applying... 
[fix-attrs.d] 01-tasmoadmin: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 

-----------------------------------------------------------
 Hass.io Add-on: TasmoAdmin v0.6.0

 Centrally manage all your Sonoff-Tasmota devices

 From: Community Hass.io Add-ons
 By: Franck Nijhof <frenck@addons.community>
-----------------------------------------------------------
 amd64 / Ubuntu 18.04.1 LTS / HA 0.79.1 / SU 132 / beta
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to INFO
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] 02-updates.sh: executing... 

INFO: You are running the latest version of this add-on
[cont-init.d] 02-updates.sh: exited 0.
[cont-init.d] 10-requirements.sh: executing... 
[cont-init.d] 10-requirements.sh: exited 0.
[cont-init.d] 11-nginx.sh: executing... 
[cont-init.d] 11-nginx.sh: exited 0.
[cont-init.d] 12-migrate.sh: executing... 
[cont-init.d] 12-migrate.sh: exited 0.
[cont-init.d] 13-persistent-data.sh: executing... 
[cont-init.d] 13-persistent-data.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.

```

**Comment by frenck** [comment]
@vajonam I totally missed this one! So sorry!

Ubuntu 18.04.1 LTS
 My guess, is you are running an incorrect version of Docker. Please be sure you are using Docker 18.09.

**Comment by vajonam** [comment]
Good point, just upgraded my installation to docker-ce,

docker --version

    Docker version 18.09.0, build 4d60db4

still seeing the same issue.

When i open a bash into the container.

root@a0d7b954-sonweb:/$ ping 10.1.1.125
PING 10.1.1.125 (10.1.1.125): 56 data bytes
64 bytes from 10.1.1.125: seq=0 ttl=253 time=85.321 ms
64 bytes from 10.1.1.125: seq=1 ttl=253 time=163.802 ms
^C
--- 10.1.1.125 ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 85.321/124.561/163.802 ms

root@a0d7b954-sonweb:/$ ping shelly1_03
ping: bad address 'shelly1_03'

root@a0d7b954-sonweb:/$ cat /etc/resolv.conf
nameserver 127.0.0.11
options ndots:0

**Comment by frenck** [comment]
Well the DNS is provided by Hass.io in this case and not in control of the add-on.
I would recommend you to open an issue with the Hass.io repository (or check similar issues in the history of the Hass.io repository).

Sorry m8! 😞

**Comment by vajonam** [comment]
Yes got it thanks, FQDN seems to work okay. i.e. host.domain.com resolves
but host does not sort of makes sense. Guess the hassio needs to propagate
the search domain to the various addon containers.

**Comment by vajonam** [comment]
please go ahead and close or invalidate.
