### ISSUE TITLE
Switch to Ingress

### ISSUE THREAD

**Issue by efaden** [hassio-addons/addon-tasmoadmin#319]
Would be nice to use ingress vs actual port.

**Comment by tjorim** [comment]
I https://github.com/hassio-addons/addon-tasmoadmin/issues/303 think https://github.com/hassio-addons/addon-tasmoadmin/issues/283 this https://github.com/hassio-addons/addon-tasmoadmin/issues/215 has https://github.com/hassio-addons/addon-tasmoadmin/issues/142 been https://github.com/hassio-addons/addon-tasmoadmin/issues/88 discussed https://github.com/hassio-addons/addon-tasmoadmin/issues/62 plenty https://github.com/hassio-addons/addon-tasmoadmin/issues/59 of https://github.com/hassio-addons/addon-tasmoadmin/issues/47 times https://github.com/hassio-addons/addon-tasmoadmin/issues/44 before.
