### ISSUE TITLE
portainer : container not healty sh: ]: unknown operand

### ISSUE THREAD

**Issue by platini76** [hassio-addons/addon-tasmoadmin#328]
related to:
https://github.com/hassio-addons/addon-tasmoadmin/issues/300

issue not solved..

**Comment by Hadatko** [comment]
I took a look into container logs and found this:
<img width="373" alt="image" src="https://github.com/hassio-addons/addon-tasmoadmin/assets/13130700/9f0b07f8-3cd5-4632-9119-d24e50eeba4c">
I would say that curl command is wrong and not working and should be fixed.
Your cmd on my laptop:
<img width="536" alt="image" src="https://github.com/hassio-addons/addon-tasmoadmin/assets/13130700/3b6f6937-6156-460b-9ab0-a3579caae71a">
Chatgpt (i know he can be wrong)
<img width="321" alt="image" src="https://github.com/hassio-addons/addon-tasmoadmin/assets/13130700/20839d46-c1fd-4dd1-843f-5fead88d6a00">
On my laptop:
<img width="594" alt="image" src="https://github.com/hassio-addons/addon-tasmoadmin/assets/13130700/47e5c861-58f7-4a5a-83c8-f20956fc1407">

With small modification i made working also your origin idea:
<img width="534" alt="image" src="https://github.com/hassio-addons/addon-tasmoadmin/assets/13130700/594bf855-54ab-466a-9824-33776a0b2efc">

**Comment by Hadatko** [comment]
Hmm i see that i got correct error but still there is 'test2.sh: 2: [[: not found' So maybe use chatgpt solution
'if ! curl --fail http://127.0.0.1:9541 >/dev/null 2>&1 && ! curl --fail --insecure https://127.0.0.1:9541 >/dev/null 2>&1; then exit 1; fi'

'if ! curl --fail http://127.0.0.1:9541  && ! curl --fail --insecure https://127.0.0.1:9541; then exit 1; fi'

**Comment by Hadatko** [comment]
@sinclairpaul

**Comment by Hadatko** [comment]
:(

**Comment by Hadatko** [comment]
As fix was merged this can be closed i think....
