### ISSUE TITLE
Unable to upgrade edge version to 2691e50

### ISSUE THREAD

**Issue by inverse** [hassio-addons/addon-tasmoadmin#330]
# Problem/Motivation

I'm unable to upgrade edge version and I suspect it's due to the way `2691e50` is being parsed.

![image](https://github.com/hassio-addons/addon-tasmoadmin/assets/713525/ddc95682-a37b-458e-ba29-938d6426ffd3)

## Expected behavior

To be able to upgrade version

## Actual behavior

Failure notification

![image](https://github.com/hassio-addons/addon-tasmoadmin/assets/713525/0ca626d1-0b19-422c-a12e-602bb9fe9c6d)

## Steps to reproduce

Install version `d284afa` and try to upgrade to `2691e50`

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
Yup, this is a known issue, that can happen on edge. Mostly caused by a different interpretation by the YAML parsers used by the repository updater & the Home Assistant Supervisor.

Just pushed a new version, which resolves it.

../Frenck
