### ISSUE TITLE
Unable to update devices

### ISSUE THREAD

**Issue by dnedeltchev** [hassio-addons/addon-tasmoadmin#331]
# Problem/Motivation
Unable to update devices using Automatic option
> (Why the issue was filed)

## Expected behavior
Update devices
> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce
Install add-on, change OTA IP to home assistant IP, click automatic update and an error comes up.

Minimal Firmware is not accessible on the server at http://192.168.1.5:9541/data/firmwares/tasmota-minimal.bin.gz
Please check the OTA IP address and port are correct
Full Firmware is not accessible on the server at http://192.168.1.5:9541/data/firmwares/tasmota.bin.gz
Please check the OTA IP address and port are correct

If I change the OTA to ota.tasmota.com and port 80, I see the list of devices to update, however, when updating, each device fails to update... I've never been able to use this add-on to update my devices. I have resorted to updating them individually however, I've now got over 10 tasmota devices and it's becoming impractical for update them individually.
> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by mjkl-gh** [comment]
This is probably the same issue as #291 

I posted a fix there https://github.com/hassio-addons/addon-tasmoadmin/issues/291#issuecomment-1614721601

Can you see if that works for you?
