### ISSUE TITLE
Failing to start

### ISSUE THREAD

**Issue by hvhol** [hassio-addons/addon-tasmoadmin#337]
# Problem/Motivation

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by speakradmin** [comment]
Same here, the first time it took ages to start but eventually did. Now it keeps showing the spinning indicator saying it's starting but never does. Log:

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting

-----------------------------------------------------------
 Add-on: TasmoAdmin
 Centrally manage all your Sonoff-Tasmota devices
-----------------------------------------------------------
 Add-on version: 0.25.0
 You are running the latest version of this add-on.
 System: Debian GNU/Linux 12 (bookworm)  (amd64 / qemux86-64)
 Home Assistant Core: 2023.8.1
 Home Assistant Supervisor: 2023.07.2
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
Log level is set to DEBUG
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-tasmoadmin: starting
s6-rc: info: service init-nginx: starting
[15:09:21] DEBUG: Symlinking data directory to persistent storage location...
s6-rc: info: service init-tasmoadmin successfully started
s6-rc: info: service php-fpm: starting
s6-rc: info: service php-fpm successfully started
[15:09:21] INFO: Starting PHP-FPM server...
s6-rc: info: service init-nginx successfully started
s6-rc: info: service nginx: starting
s6-rc: info: service nginx successfully started
s6-rc: info: service legacy-services: starting
[15:09:21] INFO: Starting NGINX server...
s6-rc: info: service legacy-services successfully started
