### ISSUE TITLE
After fresh install there is "no" register screen in Web UI - Wrong title

### ISSUE THREAD

**Issue by FajnB** [hassio-addons/addon-tasmoadmin#357]
# Problem/Motivation

> After installing this add-on and entering the Web UI for the first time, the screen is showing a "Login" instead of "Register"
This might be very confusing for newcomers and potentially troublesome for people who lost their password and reinstalled.
I my self forgot the password and had to reinstall and I was absolutely bamboozled by the initial screen as it said "Login"

## Expected behavior

> Initial setup (Opening Web UI for the first time after install) should be saying "Register"

## Actual behavior

> Currently it says "Login"

## Steps to reproduce

> This is the exact process I went through
1, Install/reinstall the add-on
2, Disable SSL and save
3, Enable watchdog
4, Start the add-on and wait till it says in log that it started successfully or Ctrl+F5 after 2-3 minutes (depends on the speed of the system)
5, Open Web UI
6, See the text saying "Login" instead of "Register" above the username and password fields

## Proposed changes

> Change text from "Login" to "Register" at the initial setup of Web UI / if the user has not been set up yet
> It will reduce the confusion of unfamiliar users as some might think there is a  default login username and password

**Comment by inverse** [comment]
This should be registered upstream in TasmoAdmin 

https://github.com/TasmoAdmin/TasmoAdmin
