### ISSUE TITLE
Can not change language on login page + language reset when logout

### ISSUE THREAD

**Issue by FajnB** [hassio-addons/addon-tasmoadmin#358]
# Problem/Motivation

> The login page can not be changed to different language.
> Related issue: > After logout the language is reset

NOTE: I have a feeling, that these two issues are closely related as common point seems to be the login page and thus I merged them into one. If needed, just tell me and I'll split them into separate issues.

## Expected behavior

> When changing language on the login screen, the language is set to the one selected by user.
> When logging out the language setting should be kept

## Actual behavior

> Currently it when language is selected, the page will refresh, but the language is still set to the (presumably, didn't tested other system languages) local language. In my case CS
> When logging out, the language changes to (presumably, didn't tested other system languages) local language.

## Steps to reproduce

> Login page
1, Open Web UI
2, Change language in top left corner
3, The page reloads and stays on the previous (presumably, didn't tested other system languages) local language

> When logging out
1, Open Web UI and login
2, Change language in top left corner
3, After website reloads and displays in selected language, logout
4, The page redirects you back to login page and changes language to the (presumably, didn't tested other system languages) local language

## Proposed changes

> The page (the login one) should keep the language selected by user no matter if while on that page or after login
> It might be bothersome if the user travels into different country and the Web UI will change the language to that local language every time. This might not be a problem as I don't know if the Web UI sources the language from the browser or the system/HASS.

**Comment by inverse** [comment]
This should be registered upstream in TasmoAdmin 

https://github.com/TasmoAdmin/TasmoAdmin
