### ISSUE TITLE
Errro in autoscan

### ISSUE THREAD

**Issue by SoundGuy** [hassio-addons/addon-tasmoadmin#36]
# Problem/Motivation
Can't Autoscan. it fails.

## Expected behavior
Auto scan should work
## Actual behavior

when running auto scan i get this error:
Recoverable fatal error: Object of class stdClass could not be converted to string in /var/www/tasmoadmin/tasmoadmin/includes/Sonoff.php on line 1000

## Steps to reproduce

I am on a clean install of Hass.io 141 with the latest Tasmoadmin 0.6.0 fresh installthough through hassio and with RPI 1b

**Comment by kennethhaspeel** [comment]
Got the same issue. Adding device manually, no problem. But autoscan produces the mentioned error.

**Comment by frenck** [comment]
Please report this issue with the TasmoAdmin project (which this add-on wraps).
It cannot be fixed from an add-on perspective.
