### ISSUE TITLE
TasmoAdmin won't open after install ssl cerificate

### ISSUE THREAD

**Issue by Fabio7586** [hassio-addons/addon-tasmoadmin#38]
# Problem/Motivation
WebUI dont works under https
it only works writing https://192.168.2.11:9541/
but it give a warning because it doesn't recognize certificate.

Please help me!
![https warning](https://user-images.githubusercontent.com/11045183/53726815-14a28d00-3e6f-11e9-9462-501f9900c363.jpg)

> (Why the issue was filed)

## Expected behavior
WebUI work
> (What you expected to happen)

## Actual behavior
WebUI work only under http
actual config
`{
  "log_level": "debug",
  "ssl": true,
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem",
  "ipv6": false
}`
> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)
## log
`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-tasmoadmin: applying... 
[fix-attrs.d] 01-tasmoadmin: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 

 Hass.io Add-on: TasmoAdmin v0.6.1
 Centrally manage all your Sonoff-Tasmota devices
 From: Community Hass.io Add-ons
 By: Franck Nijhof <frenck@addons.community>

 aarch64 / HassOS 2.10 / HA 0.88.2 / SU 145 / stable

[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to DEBUG
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] 02-updates.sh: executing... 
DEBUG: Requested API resource: http://hassio/supervisor/ping
DEBUG: API HTTP Response code: 200
DEBUG: API Response: {"result": "ok", "data": {}}
DEBUG: Requested API resource: http://hassio/addons/self/info
DEBUG: API HTTP Response code: 200
DEBUG: API Response: {"result": "ok", "data": {"name": "TasmoAdmin", "slug": "a0d7b954_sonweb", "description": "Centrally manage all your Sonoff-Tasmota devices", "long_description": "# Community Hass.io Add-ons: TasmoAdmin\n\n[![Release][release-shield]][release] ![Project Stage][project-stage-shield] ![Project Maintenance][maintenance-shield]\n\n[![Discord][discord-shield]][discord] [![Community Forum][forum-shield]][forum]\n\n[![Buy me a coffee][buymeacoffee-shield]][buymeacoffee]\n\n[![Support my work on Patreon][patreon-shield]][patreon]\n\nCentrally manage all your Sonoff-Tasmota devices.\n\n## About\n\nTasmoAdmin (formerly known as SonWEB) is an administrative web interface to\nmanage all your Sonoff-Tasmota flashed devices centrally.\nSome of its features:\n\n- Scans your networks and adds your devices automatically\n- See the status off all your devices quick and easy\n- Configure all your devices from a single place\n- Send out firmware updates over the air to one or more your devices at once\n- Can automatically download the latest firmware for you\n\n[Click here for the full documentation][docs]\n\n![TasmoAdmin screenshot][screenshot]\n\n[buymeacoffee-shield]: https://www.buymeacoffee.com/assets/img/guidelines/download-assets-sm-2.svg\n[buymeacoffee]: https://www.buymeacoffee.com/frenck\n[discord-shield]: https://img.shields.io/discord/478094546522079232.svg\n[discord]: https://discord.me/hassioaddons\n[docs]: https://github.com/hassio-addons/addon-tasmoadmin/blob/v0.6.1/README.md\n[forum-shield]: https://img.shields.io/badge/community-forum-brightgreen.svg\n[forum]: https://community.home-assistant.io/t/community-hass-io-add-on-tasmoadmin/54155?u=frenck\n[maintenance-shield]: https://img.shields.io/maintenance/yes/2019.svg\n[patreon-shield]: https://www.frenck.nl/images/patreon.png\n[patreon]: https://www.patreon.com/frenck\n[project-stage-shield]: https://img.shields.io/badge/project%20stage-experimental-yellow.svg\n[release-shield]: https://img.shields.io/badge/version-v0.6.1-blue.svg\n[release]: https://github.com/hassio-addons/addon-tasmoadmin/tree/v0.6.1\n[screenshot]: https://github.com/hassio-addons/addon-tasmoadmin/raw/master/images/screenshot.png", "version": "0.6.1", "auto_update": false, "repository": "a0d7b954", "last_version": "0.6.1", "state": "started", "protected": true, "rating": 5, "boot": "auto", "options": {"log_level": "debug", "ssl": true, "certfile": "fullchain.pem", "keyfile": "privkey.pem", "ipv6": false}, "arch": ["aarch64", "amd64", "armhf", "i386"], "machine": ["intel-nuc", "odroid-c2", "odroid-xu", "orangepi-prime", "qemux86", "qemux86-64", "qemuarm", "qemuarm-64", "raspberrypi", "raspberrypi2", "raspberrypi3", "raspberrypi3-64", "tinker"], "url": "https://github.com/hassio-addons/addon-tasmoadmin", "detached": false, "available": true, "build": false, "network": {"9541/tcp": 9541}, "host_network": false, "host_pid": false, "host_ipc": false, "host_dbus": false, "privileged": [], "full_access": false, "apparmor": "default", "devices": null, "icon": true, "logo": true, "changelog": true, "webui": "https://[HOST]:9541", "stdin": false, "hassio_api": true, "hassio_role": "default", "auth_api": false, "homeassistant_api": false, "gpio": false, "kernel_modules": false, "devicetree": false, "docker_api": false, "audio": false, "audio_input": null, "audio_output": null, "services": [], "discovery": []}}
DEBUG: Filtering response using: .version
DEBUG: Requested API resource: http://hassio/addons/self/info
DEBUG: API HTTP Response code: 200
DEBUG: API Response: {"result": "ok", "data": {"name": "TasmoAdmin", "slug": "a0d7b954_sonweb", "description": "Centrally manage all your Sonoff-Tasmota devices", "long_description": "# Community Hass.io Add-ons: TasmoAdmin\n\n[![Release][release-shield]][release] ![Project Stage][project-stage-shield] ![Project Maintenance][maintenance-shield]\n\n[![Discord][discord-shield]][discord] [![Community Forum][forum-shield]][forum]\n\n[![Buy me a coffee][buymeacoffee-shield]][buymeacoffee]\n\n[![Support my work on Patreon][patreon-shield]][patreon]\n\nCentrally manage all your Sonoff-Tasmota devices.\n\n## About\n\nTasmoAdmin (formerly known as SonWEB) is an administrative web interface to\nmanage all your Sonoff-Tasmota flashed devices centrally.\nSome of its features:\n\n- Scans your networks and adds your devices automatically\n- See the status off all your devices quick and easy\n- Configure all your devices from a single place\n- Send out firmware updates over the air to one or more your devices at once\n- Can automatically download the latest firmware for you\n\n[Click here for the full documentation][docs]\n\n![TasmoAdmin screenshot][screenshot]\n\n[buymeacoffee-shield]: https://www.buymeacoffee.com/assets/img/guidelines/download-assets-sm-2.svg\n[buymeacoffee]: https://www.buymeacoffee.com/frenck\n[discord-shield]: https://img.shields.io/discord/478094546522079232.svg\n[discord]: https://discord.me/hassioaddons\n[docs]: https://github.com/hassio-addons/addon-tasmoadmin/blob/v0.6.1/README.md\n[forum-shield]: https://img.shields.io/badge/community-forum-brightgreen.svg\n[forum]: https://community.home-assistant.io/t/community-hass-io-add-on-tasmoadmin/54155?u=frenck\n[maintenance-shield]: https://img.shields.io/maintenance/yes/2019.svg\n[patreon-shield]: https://www.frenck.nl/images/patreon.png\n[patreon]: https://www.patreon.com/frenck\n[project-stage-shield]: https://img.shields.io/badge/project%20stage-experimental-yellow.svg\n[release-shield]: https://img.shields.io/badge/version-v0.6.1-blue.svg\n[release]: https://github.com/hassio-addons/addon-tasmoadmin/tree/v0.6.1\n[screenshot]: https://github.com/hassio-addons/addon-tasmoadmin/raw/master/images/screenshot.png", "version": "0.6.1", "auto_update": false, "repository": "a0d7b954", "last_version": "0.6.1", "state": "started", "protected": true, "rating": 5, "boot": "auto", "options": {"log_level": "debug", "ssl": true, "certfile": "fullchain.pem", "keyfile": "privkey.pem", "ipv6": false}, "arch": ["aarch64", "amd64", "armhf", "i386"], "machine": ["intel-nuc", "odroid-c2", "odroid-xu", "orangepi-prime", "qemux86", "qemux86-64", "qemuarm", "qemuarm-64", "raspberrypi", "raspberrypi2", "raspberrypi3", "raspberrypi3-64", "tinker"], "url": "https://github.com/hassio-addons/addon-tasmoadmin", "detached": false, "available": true, "build": false, "network": {"9541/tcp": 9541}, "host_network": false, "host_pid": false, "host_ipc": false, "host_dbus": false, "privileged": [], "full_access": false, "apparmor": "default", "devices": null, "icon": true, "logo": true, "changelog": true, "webui": "https://[HOST]:9541", "stdin": false, "hassio_api": true, "hassio_role": "default", "auth_api": false, "homeassistant_api": false, "gpio": false, "kernel_modules": false, "devicetree": false, "docker_api": false, "audio": false, "audio_input": null, "audio_output": null, "services": [], "discovery": []}}
DEBUG: Filtering response using: .last_version
INFO: You are running the latest version of this add-on
[cont-init.d] 02-updates.sh: exited 0.
[cont-init.d] 10-requirements.sh: executing... 
[cont-init.d] 10-requirements.sh: exited 0.
[cont-init.d] 11-nginx.sh: executing... 
[cont-init.d] 11-nginx.sh: exited 0.
[cont-init.d] 12-migrate.sh: executing... 
[cont-init.d] 12-migrate.sh: exited 0.
[cont-init.d] 13-persistent-data.sh: executing... 
DEBUG: Symlinking data directory to persistent storage location...
[cont-init.d] 13-persistent-data.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.`

**Comment by frenck** [comment]
That is to be expected with the example given.

`https://192.168.2.11:9541/`

SSL certificates are based upon domain names, not IP addresses. Accessing the web page using the IP address, makes the certificate invalid. Accessing the web page using the domain that matches the SSL certificate will work.

This is just how SSL works and not an issue with the add-on.

Closing this issue.

**Comment by Fabio7586** [comment]
As you can see in attachment writing domain names it response me with an error. I have posted issue saying that only way to show tasmoadmin page was writing ip address.

![issue](https://user-images.githubusercontent.com/11045183/53727921-bc20bf00-3e71-11e9-8344-56ce8b55e75b.jpg)

**Comment by frenck** [comment]
Seems to me like there is not port forwarding rule to support that.
Please note: If you are not exposing the add-on to the outside world (which you, in general, should avoid if not needed), then disabling SSL is the right thing to do.

**Comment by Fabio7586** [comment]
So, without static ip address i cannot make work with ssl, right?

**Comment by frenck** [comment]
That is not what I said. Please read it again and read a bit about how SSL works. If you have additional questions, please join our Discord server. We try to keep GitHub issues for issue tracking, not support.

**Comment by Fabio7586** [comment]
Ok nevermind. I will try to solve myself.

**Comment by frenck** [comment]
@Fabio7586 Good luck 👍 
Again, in case you run into troubles or need additional help, we are available on the Discord chat server to help you out. 👍
