### ISSUE TITLE
panel_iframe being removed from HomeAssistant

### ISSUE THREAD

**Issue by Will-wastelander** [hassio-addons/addon-tasmoadmin#392]
# Problem/Motivation

> Home Assistant is removing panel_iframe

## Expected behavior

> Allow Tasmota Admin to be embedded like other addons.

## Actual behavior

> Have to use panel_iframe to have Tasmota Admin embedded. panel_iframe is being removed in 2024.10.0

## Steps to reproduce

> ![image](https://github.com/hassio-addons/addon-tasmoadmin/assets/71540407/0471c98a-d699-4f2c-9e5d-972e7852ee72)

## Proposed changes

> Update to include tasmota admin in Home Assistant natively

**Comment by frenck** [comment]
> Home Assistant is removing panel_iframe

No, it is not. It is migrating to the UI.

../Frenck

**Comment by ajw107** [comment]
Sorry to comment on a closed case, but I think for nr=ew users (certainly from 2024.10 onwards) the Documentation will still need to be changed to allow them to integrate it (I assume the migration will stop working then, or at least it seems a bit bad to reply on Home Assistant to correct things due to out of date documentation).

**Comment by Will-wastelander** [comment]
> > Home Assistant is removing panel_iframe
> 
> No, it is not. It is migrating to the UI.
> 
> ../Frenck

Ok, I'll let HomeAssistant devs know this, since they are the ones saying it will be removed.. And having the addon integrated like all the other addons, isn't possible I guess. I wonder how all the other addons are integrating into HomeAssistant then....

**Comment by Will-wastelander** [comment]
I confirmed w/ HA that panel_iframe IS being removed. However they have an migration process built into HA, that when upgraded it added tasmota admin as a dashboard. So all that is needed, is to remove the manual configs from configuration.yaml file.
