### ISSUE TITLE
Name doesn't match Hostname

### ISSUE THREAD

**Issue by josephperry** [hassio-addons/addon-tasmoadmin#40]
# Problem/Motivation

>Name doesn't match Hostname if the sonoff device obtains a new IP address
## Expected behavior

>Name to match Hostname after sonoff devices obtain new DHCP address event though the other fields appear to contain the correct information
## Actual behavior

> Device keeps the original Name from the first Autoscan
## Steps to reproduce

> Cycle power on multiple sonoff devices so the DHCP server assigns different IP addresses

## Proposed changes
Have the Name match the Hostname after an Autoscan
> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
Hi there,

The add-on wraps TasmoAdmin software, which can be found here:

<https://github.com/reloxx13/TasmoAdmin>

Please report your feature requests to them, since there is nothing I can do for that.
