### ISSUE TITLE
Tasmoadmin Addon does not open URLs, eg. device web page or documentation, when running in Homeassistant App

### ISSUE THREAD

**Issue by nobthenob** [hassio-addons/addon-tasmoadmin#414]
# Problem/Motivation

In list view Tasmoadmin does not open the device web page or documentation URL
HA Core 2024.6.4
Tasmoadmin 4.1.1

## Expected behavior

The Tasmota web surface or documentation URL should open

## Actual behavior

Nothing happens

## Steps to reproduce

Click on the device name in list view, that is marked as a link.

## Proposed changes

Is it a bug, or a problem of my homeassistant setup?

Thank you for taking care.
nob

**Comment by inverse** [comment]
Does it open a new window/tab when opening or just clicking does nothing?

it should spawn a new window with the auth params filled in if you've set them for the device.

**Comment by nobthenob** [comment]
I noticed, I forget to mention, that I am mostly using the Homeassistant App on a tablet and mobile Phone.
Here Nothing happens, when click on the device link or the documentation entry in the Menü.
I just checked, that when I run HA in a browser, everything works as expected. 
So it seems to be a problem with the HA app or a setup issue?

**Comment by inverse** [comment]
Just confirmed this doesn't work. It must be a restriction enforced by the app. 

Perhaps create an issue in the app for the ecosystem you're facing the problem on.

Not much we can do in this one.

**Comment by nobthenob** [comment]
Have also reported the issue here: [https://github.com/home-assistant/android/issues/4488](https://github.com/home-assistant/android/issues/4488)
