### ISSUE TITLE
Update Devices - Automatic - not work

### ISSUE THREAD

**Issue by radim-ek** [hassio-addons/addon-tasmoadmin#426]
If you try to Automatic update. You get a error if you wrote IP adrees as is described in  **OTA Server IP**
```
Minimal Firmware is not accessible on the server at http://65.9.95.22:80/data/firmwares/tasmota-minimal.bin.gz
Please check the OTA IP address and port are correct
Full Firmware is not accessible on the server at http://65.9.95.22:80/data/firmwares/tasmota-CZ.bin.gz
Please check the OTA IP address and port are correct
```

And if you left as default: 
`Minimal Firmware is not accessible on the server at http://ota.tasmota.com/tasmota/release/:80/data/firmwares/tasmota-minimal.bin.gz
Please check the OTA IP address and port are correct
Full Firmware is not accessible on the server at http://ota.tasmota.com/tasmota/release/:80/data/firmwares/tasmota-CZ.bin.gz
Please check the OTA IP address and port are correct`

Problem is in string join:

"http://" + OTA IP + PORT

Right adresses are:
http://ota.tasmota.com/tasmota/release/tasmota-CZ.bin.gz
http://ota.tasmota.com/tasmota/release/tasmota-minimal.bin.gz

So, dont use PORT (because http is 80) and repair URL adress

**Comment by nazar-pc** [comment]
I also tried "Automatic", it did some retries, but ultimately nothing happened.

Now when I open `upload_form` "Automatic" button is not clickable and requires "OTA Server IP" (which was previously set to 127.0.0.1). I was very confused and there doesn't seem to be any documentation on this.

Then I figured out that it is supposed to be the IP address of the Home Assistant instance on which TasmotaAdmin is running.
Then things actually worked out and upgrade finished successfully.

I hope this helps someone.
