### ISSUE TITLE
TasmoAdmin: unable to start anymore

### ISSUE THREAD

**Issue by lollo78** [hassio-addons/addon-tasmoadmin#437]
Hi, TasmoAdmin stopped working on my Rpi 3.
If I try to Start it nothing happens, but logs report a lot of "exec /init: exec format error".
I tried to unistall it, reboot and reinstall, but nothing...

My specs:
Core 2024.10.3
Supervisor 2024.10.2
Operating System 13.2
Frontend 20241002.3

Any advice?
Thanks

**Comment by inverse** [comment]
Are other addons working? It sounds like an issue with the supervisor.

**Comment by lollo78** [comment]
Yes, the other 13 addons are working fine (also Nginix is good). The only issue is with Tasmoadmin.

**Comment by lollo78** [comment]
> Are other addons working? It sounds like an issue with the supervisor.

Same issue with SQLite Web addon.

**Comment by ron84088** [comment]
> Hi, TasmoAdmin stopped working on my Rpi 3. If I try to Start it nothing happens, but logs report a lot of "exec /init: exec format error". I tried to unistall it, reboot and reinstall, but nothing...
> 
> My specs: Core 2024.10.3 Supervisor 2024.10.2 Operating System 13.2 Frontend 20241002.3
> 
> Any advice? Thanks

Hi, try to switch off 'SSL' in TasmoAdmin configuration; you are probably not using SSL in HA. Solved it in my case.

**Comment by lollo78** [comment]
TasmoAdmin 0.31.0 solved the issue.

**Comment by oferbar** [comment]
I have 0.31.2 and got the same error. Disabling SSL in the configuration as suggested here actually solved the issue.
