### ISSUE TITLE
add ingress support

### ISSUE THREAD

**Issue by Fma965** [hassio-addons/addon-tasmoadmin#44]
https://www.home-assistant.io/blog/2019/04/15/hassio-ingress/

Please :) 

<blockquote><img src="https://www.home-assistant.io/images/blog/2019-04-hassio-ingress/blogpost.png" width="48" align="right"><div><img src="/images/favicon-192x192.png" height="14"> Home Assistant</div><div><strong><a href="https://www.home-assistant.io/blog/2019/04/15/hassio-ingress/">Introducing Hass.io Ingress</a></strong></div><div>Ingress allows Hass.io add-ons to seamlessly integrate their user interface with Home Assistant</div></blockquote>

**Comment by frenck** [comment]
This add-on cannot support ingress due to technical limitations.
