### ISSUE TITLE
How to integrate TasmoAdmin into HA sidebar?

### ISSUE THREAD

**Issue by ron84088** [hassio-addons/addon-tasmoadmin#440]
TasmoAdmin formerly used to integrate into the sidebar and client window of HA, like shown in the documentation. 

With current HA versions, this nice feature seem to be gone?
My current workaround is to create a dashboard with a web card...

**Comment by frenck** [comment]
> TasmoAdmin formerly used to integrate into the sidebar and client window of HA

Incorrect.

> like shown in the documentation.

That is an iframe.

> With current HA versions, this nice feature seem to be gone?

Nope. Still there.

> My current workaround is to create a dashboard with a web card...

Yup, that's it.


../Frenck
