### ISSUE TITLE
New version is 0.4.1 instead of 0.7.1 ?

### ISSUE THREAD

**Issue by alessio-papi** [hassio-addons/addon-tasmoadmin#45]
# Problem/Motivation

Reuse of past version number

## Expected behavior

The version should be greater than 0.7.0

## Actual behavior

Add-on shows version 0.4.1

## Steps to reproduce

Connect do HA add-on management and it will propose to update to 0.4.1 from 0.7.0

## Proposed changes

Tag as new version if possibile

**Comment by frenck** [comment]
Correct, sorry about that!
