### ISSUE TITLE
Add link in 'Install' section to manual install procedure without addon repository

### ISSUE THREAD

**Issue by jhalbrecht** [hassio-addons/addon-tasmoadmin#48]
As a convenience for folks that land here while searching how to manually install tasmoadmin without benefit of a hass.io install with addon store / repositories may I suggest we add a short perhaps one liner to point to the solution?

I found out how to install [tasmoadmin manually here;](https://github.com/arendst/Sonoff-Tasmota/wiki/TasmoAdmin#installation) I think it would be helpful to add a link to that page in the [Install portion of this page](https://github.com/hassio-addons/addon-tasmoadmin#installation)
I spent some time searching and forum reading before I found what in retrospect is obvious... (DOH!)

Discussion? I can create a pull request if desired. :-)

**Comment by frenck** [comment]
No thanks, the focus for the Community Hass.io Add-ons is Hass.io.
