### ISSUE TITLE
Selecting multiple devices for deletion

### ISSUE THREAD

**Issue by Stretcherfetcher** [hassio-addons/addon-tasmoadmin#49]
# Problem/Motivation

After router reboot/network issues many of the devices will have a new ip address and a require a rescan. This results in duplicate devices requiring deletion.

## Actual behavior

Each device must be selected and deleted individually. This can be a slow process if there are many devices on new ip's

## Proposed changes

The ability to select multiple devices for deletion would be advantageous.

**Comment by frenck** [comment]
Hi,

Thanks! But that is a feature request to TasmoAdmin itself, not the add-on.
Please file a feature request with the TasmoAdmin project.

👍

**Comment by Stretcherfetcher** [comment]
Thanks Frenck, noob mistake !
