### ISSUE TITLE
Error when searching for devices , cant add the discovered devices

### ISSUE THREAD

**Issue by gnkarn** [hassio-addons/addon-tasmoadmin#5]
# Problem/Motivation
error when searching for active devices

Notice: Undefined property: stdClass::$StatusNET in /var/www/sonweb/pages/devices_autoscan.php on line 61

Notice: Trying to get property of non-object in /var/www/sonweb/pages/devices_autoscan.php on line 61

Notice: Undefined offset: 3 in /var/www/sonweb/pages/devices_autoscan.php on line 62

Notice: Undefined property: stdClass::$StatusNET in /var/www/sonweb/pages/devices_autoscan.php on line 61

Notice: Trying to get property of non-object in /var/www/sonweb/pages/devices_autoscan.php on line 61

Notice: Undefined offset: 3 in /var/www/sonweb/pages/devices_autoscan.php on line 62

**the first device identified is not a device , and this is the information showed on the ip field :** 
`<br /><b>Notice</b>:  Undefined property: stdClass::$StatusNET in <b>/var/www/sonweb/pages/devices_autoscan.php</b> on line <b>233</b><br /><br /><b>Notice</b>:  Trying to get property of non-object in <b>/var/www/sonweb/pages/devices_autoscan.php</b> on line <b>233</b><br />`

 devices are detected correctly , ( not all of them , some are missing from the list) ,  but as this device #1 cant be deleted , there is no actual way to include the discovered devices .

![screen shot 2018-05-30 at 20 02 32](https://user-images.githubusercontent.com/3314004/40752104-820df51a-6444-11e8-8fe2-23938f292421.png)

**Comment by gnkarn** [comment]
more info , by completing the empty field ,  the discovered devices where added .
still i need to  see why there some divices that were not discovered ..

thanks , for this addon !

**Comment by frenck** [comment]
Glad the issue has been solved.
The new version might approve on this as well!
