### ISSUE TITLE
TasmoAdmin no start no log

### ISSUE THREAD

**Issue by maxgiordan** [hassio-addons/addon-tasmoadmin#50]
# Problem/Motivation

> I installed this addon but it doesn't start
## Expected behavior

> That at least log started ... but nothing at all

## Actual behavior

> Nothing, I click on start but, after a second, red light and no log

## Steps to reproduce

> I attach a screenshot

## Proposed changes

I tried uninstalling and reinstalling after restarting hassio, but nothing, not even the log.
This is my configuration:
`{
  "ssl": true,
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem",
  "log_level": "info"
}`

![1](https://user-images.githubusercontent.com/51880181/62460055-39ce5b00-b781-11e9-9d67-aee6a59a2cf8.png)

**Comment by frenck** [comment]
Please check the Supervisor log: Hass.io Panel -> System Tab -> Logs

**Comment by maxgiordan** [comment]
Thaso much frenck, I tried to uninstall and reinstall again: now it's magically gone but I don't have access to web ui.
This is debug mode log:

`Log
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-tasmoadmin: applying... 
[fix-attrs.d] 01-tasmoadmin: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Hass.io Add-on: TasmoAdmin
 Centrally manage all your Sonoff-Tasmota devices
-----------------------------------------------------------
 Add-on version: 0.8.1
 You are running the latest version of this add-on.
 System: HassOS 2.12  (aarch64 / raspberrypi3-64)
 Home Assistant version: 0.96.5
 Supervisor version: 170
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to DEBUG
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] tasmoadmin.sh: executing... 
[15:17:56] DEBUG: Symlinking data directory to persistent storage location...
[cont-init.d] tasmoadmin.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[15:17:56] INFO: Starting PHP-FPM server...
[15:17:56] INFO: Starting NGinx server...`

Hassio System Log:

`19-08-06 12:59:58 INFO (MainThread) [hassio.homeassistant] Detect a running Home Assistant instance
19-08-06 13:00:01 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request initialize
19-08-06 13:00:01 INFO (MainThread) [hassio.api.proxy] WebSocket access from a0d7b954_appdaemon3
19-08-06 13:00:01 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request running
19-08-06 13:04:58 INFO (MainThread) [hassio.updater] Fetch update data from https://version.home-assistant.io/stable.json
19-08-06 13:07:21 INFO (MainThread) [hassio.addons] Create Home Assistant add-on data folder /data/addons/data/a0d7b954_sonweb
19-08-06 13:07:21 INFO (SyncWorker_9) [hassio.docker.interface] Pull image hassioaddons/sonweb-aarch64 tag 0.8.1.
19-08-06 13:07:23 INFO (SyncWorker_9) [hassio.docker.interface] Tag image hassioaddons/sonweb-aarch64 with version 0.8.1 as latest
19-08-06 13:10:02 INFO (MainThread) [hassio.homeassistant] Updated Home Assistant API token
19-08-06 13:10:49 INFO (SyncWorker_17) [hassio.docker.addon] Start Docker add-on hassioaddons/sonweb-aarch64 with version v0.8.1
19-08-06 13:11:30 INFO (MainThread) [hassio.api.security] /host/info access from a0d7b954_sonweb
19-08-06 13:16:19 INFO (SyncWorker_0) [hassio.docker.interface] Stop addon_a0d7b954_sonweb application
19-08-06 13:16:21 INFO (SyncWorker_0) [hassio.docker.interface] Clean addon_a0d7b954_sonweb application
19-08-06 13:16:24 INFO (SyncWorker_7) [hassio.docker.addon] Start Docker add-on hassioaddons/sonweb-aarch64 with version v0.8.1
19-08-06 13:17:46 INFO (MainThread) [hassio.api.security] /host/info access from a0d7b954_sonweb`

**Comment by frenck** [comment]
The logs look fine, so it seems to me that you are having other issues.
Try accessing it directly on `http://IP:PORT` or `https://IP:PORT`.

**Comment by maxgiordan** [comment]
Eh frenck, are you right, do you think if I don't enable port 9541 can it ever work? I'm providing now ...

**Comment by maxgiordan** [comment]
Perfect! Everything ok, thanks frenck, it goes very well: you are great!
