### ISSUE TITLE
Tasmoadmin in Hassio Ingress or working panel_iframe if using your "Nginx Proxy Manager"

### ISSUE THREAD

**Issue by Paco1960** [hassio-addons/addon-tasmoadmin#51]
Hi Franck,
I'm trying to add your Tasmoadmin in sidebar.
You've already answered that modifying it for ingress is too difficult.
I'm successfully using your "Nginx Proxy Manager" addon to access remotely my Hassio (all, Hassio and addons locally in http, not https), but I'm not able to configure panel_iframe and/or Tasmoadmin to be shown in left window.
Tested both activating and deactivating SSL, no success.
Saw that Tasmoadmin also uses NGINX... may be the cause?

Could you explain how to solve?

Thanks in advance!

**Comment by jncanches** [comment]
+1 here.
Wonder how to configure my own nginx to access tasmoadmin remotely

**Comment by NdK73** [comment]
Similar issue here: I'm using Apache as reverse proxy. Currently only  ports 80, 443 and 8123 are allowed.

**Comment by sinclairpaul** [comment]
Browser Console/Proxy logs would probably be helpful, along with some form of config tried.  As the addon does not use Ingress, your browser needs to connect to the port that the addon listens on, either directly, or through a configured proxy that forwards to that port.

**Comment by frenck** [comment]
unfortunately, not all application behave well with a reverse proxy. So does the TasmoAdmin application.
