### ISSUE TITLE
sonoff gives a problem.

### ISSUE THREAD

**Issue by Skottelbraai** [hassio-addons/addon-tasmoadmin#53]
JSON Antwoord => {"Status":{"Model":1, "FriendlyName":"Sonoff", "Topic":"pomp", "ButtonTopic":"0", "Subtopic":"POWER", "Power":0, "PowerOnState":3, "LedState":1, "SaveData":1, "SaveState":1, "ButtonRetain":0, "PowerRetain":0}}RESULT = {"StatusPRM":{"Baudrate":115200, "GroupTopic":"sonoffs", "OtaUrl":"http://domus1:80/api/arduino/sonoff.ino.bin", "Uptime":199, "Sleep":0, "BootCount":473, "SaveCount":936}}RESULT = {"StatusFWR":{"Program":"3.2.13", "Boot":6, "SDK":"1.5.3(aec24ac9)"}}RESULT = {"StatusLOG":{"Seriallog":2, "Weblog":2, "Syslog":0, "LogHost":"domus1", "SSId1":"Frank", "SSId2":"indebuurt2", "TelePeriod":300}}RESULT = {"StatusMEM":{"ProgramSize":396, "Free":92, "Heap":12, "SpiffsStart":492, "SpiffsSize":512, "FlashSize":1024, "ProgramFlashSize":1024}}RESULT = {"StatusNET":{"Host":"pomp-1991", "IP":"192.168.1.42", "Gateway":"192.168.1.1", "Subnetmask":"255.255.255.0", "Mac":"EC:FA:BC:8A:67:C7", "Webserver":2, "WifiConfig":3}}RESULT = {"StatusMQT":{"Host":"192.168.1.91", "Port":1883, "ClientMask":"DVES_%06X", "Client":"DVES_8A67C7", "User":"DVES_USER", "MAX_PACKET_SIZE":1000, "KEEPALIVE":15}}RESULT = {"StatusTIM":{"UTC":"Wed Sep 25 18:52:00 2019", "Local":"Wed Sep 25 19:52:00 2019", "StartDST":"Sun Mar 31 02:00:00 2019", "EndDST":"Sun Oct 27 03:00:00 2019", "Timezone":1}}

Any ideas?

**Comment by sinclairpaul** [comment]
What are we looking at here?, perhaps you could be a bit more descriptive if the issue you are experiencing and why you think it could be related to the addon?

**Comment by frenck** [comment]
This is a response that isn't handled correctly.
The add-on wraps TasmoAdmin software, this is an issue on their side, please report the issue with TasmoAdmin itself. Thanks! 👍
