### ISSUE TITLE
Show in sidebar

### ISSUE THREAD

**Issue by ichilton** [hassio-addons/addon-tasmoadmin#54]
Hi,

Thanks for your work on this addon - it's really useful.

A small feature request - a lot of hassio addons now have a "Show in sidebar" option (next to 'start on boot' etc).

Please could this be added to tasmoadmin?

Thanks,

Ian

**Comment by frenck** [comment]
The upstream development of TasmoAdmin has stalled. I'm not planning on adding new features to an add-on without the future at this point.

If the project resurrects, I'm happy to add it to the add-on.

**Comment by whc2001** [comment]
> The upstream development of TasmoAdmin has stalled. I'm not planning on adding new features to an add-on without the future at this point.
> 
> If the project resurrects, I'm happy to add it to the add-on.

Seems like the original TasmoAdmin has become active again on Oct 27. Also looking forward to the "Show in sidebar" feature.
