### ISSUE TITLE
Error in update firmware

### ISSUE THREAD

**Issue by rafuz** [hassio-addons/addon-tasmoadmin#56]
# Problem/Motivation

> Unable to download updated firmware from github

## Expected behavior

> Automatic download of firmware from github

## Actual behavior

> When trying automatic update of firmware I get this errors:
```

Notice: Undefined property: stdClass::$assets in /var/www/tasmoadmin/tasmoadmin/pages/upload.php on line 174

Warning: Invalid argument supplied for foreach() in /var/www/tasmoadmin/tasmoadmin/pages/upload.php on line 174

```
## Steps to reproduce

> Just click on "Update" in device menu.

`Warning: strpos(): Offset not contained in string in /var/www/tasmoadmin/tasmoadmin/pages/upload_form.php on line 59`

## Proposed changes

> No idea on how to fix this

**Comment by sinclairpaul** [comment]
Looks to be related to changes in Tasmota, and may be fixed in another beta release of TasmoAdmin

**Comment by sinclairpaul** [comment]
This should be resolved with the latest release.
