### ISSUE TITLE
7.1.1.1 not supported

### ISSUE THREAD

**Issue by clsferguson** [hassio-addons/addon-tasmoadmin#58]
tasmota's version 7.1.1.1 is not connecting to TasmoAdmin.

Issue was resolved on main tasmoadmin branch.

https://github.com/reloxx13/TasmoAdmin/issues/326

**Comment by sinclairpaul** [comment]
Thanks for logging the issue, to save having to read through the whole issue log, perhaps you could confirm the release this is fixed in?

**Comment by sinclairpaul** [comment]
Found the link, appears to be fixed in 1.6.2 which was released 8 hours ago.

**Comment by clsferguson** [comment]
Yep. That sounds about right. I'm not sure how the hassio addons version references the main git versions. I'm still new to this.

Thanks,
Cory

________________________________

**Comment by clsferguson** [comment]
I just found the bug with my setup. Started reading the issues and saw it was fixed. Got confused since my tasmoadmin addons said it was the latest version. Then realized they are different, and it appeared to not have been reported to you yet. lol.

Thanks,
Cory

________________________________

**Comment by frenck** [comment]
Add-on has been updated with the latest TasmoAdmin, which should address this issue.
