### ISSUE TITLE
Hass.io Ingress

### ISSUE THREAD

**Issue by ohadlevy** [hassio-addons/addon-tasmoadmin#59]
# Problem/Motivation

> (Why the issue was filed)

I would like to use Hass.io Ingress instead of opening a new network port

## Expected behavior

No additional network ports needs to be opened in order to access tasmotaadmin.

thanks!

**Comment by ohadlevy** [comment]
oh, I just saw #47 :(

Could you please expand on the reasoning?

thanks

**Comment by frenck** [comment]
Not all applications can support Ingress, simple as that.

**Comment by ohadlevy** [comment]
thanks for looking into it, reading https://developers.home-assistant.io/docs/en/next/hassio_addon_presentation.html#ingress I couldn't understand which part won't work, is it for OTA upgrades?

**Comment by frenck** [comment]
I've added Ingress to most add-ons that support it now.
Yes, the firmware is served from it as well, which is not going to work with Ingress.

Furthermore, PHP applications are hard to Ingress, unfortunately. This is mainly due to a stubborn PHP FPM server that screws up the path handling.

**Comment by ohadlevy** [comment]
thanks...

**Comment by ohadlevy** [comment]
regarding path handling, there is a line there mentioning 
> If the application doesn't support relative paths or you can't set a base url, you can use nginx filter to replace the URL with correct path.

**Comment by frenck** [comment]
Yes, which breaks the non-ingress variant in that case.
