### ISSUE TITLE
update error when flashing

### ISSUE THREAD

**Issue by HFeenstra** [hassio-addons/addon-tasmoadmin#6]
# Problem/Motivation

> when updating the sonoff device it comes with this error

## Expected behavior

> To update the software to the latest Tasmoa software

## Actual behavior

> I do get these failures:
[10-51-2018 14:46:55][GLOBAAL] Start update proces
[10-51-2018 14:46:55][ID-1][STAP-1][GLOBAAL] Start Stap 1
[10-51-2018 14:46:55][ID-1][STAP-1][CONTROLEER] Controleer verbinding | PROBEER => 1
[10-51-2018 14:46:56][ID-1][STAP-1][CONTROLEER] FOUT: Apparaat heeft niet gereageerd! | MSG => JSON FOUT => 4: Syntax error
Kopieer de hele foutmelding en plak deze in een nieuwe bevinding op GitHUB. Op de een of andere manier gereageerde de Tasmota Firmware met een onjuiste JSON string, welke verwerkt dient te worden in TasmoAdmin. 
JSON Antwoord => Status, Data Size 1, Data 213:46:56 RSL: Group 0, Index 1, Command STATUS, Data 2{"StatusFWR":{"Version":"5.10.0","BuildDateTime":"2017-12-29T11:40:24","Boot":4,"Core":"2_3_0","SDK":"1.5.3(aec24ac9)"}}
[10-51-2018 14:46:56][ID-1][STAP-1][CONTROLEER] Controleer verbinding | PROBEER => 2
[10-51-2018 14:46:56][ID-1][STAP-1][CONTROLEER] FOUT: Apparaat heeft niet gereageerd! | MSG => JSON FOUT => 4: Syntax error
Kopieer de hele foutmelding en plak deze in een nieuwe bevinding op GitHUB. Op de een of andere manier gereageerde de Tasmota Firmware met een onjuiste JSON string, welke verwerkt dient te worden in TasmoAdmin. 
JSON Antwoord => Status, Data Size 1, Data 213:46:56 RSL: Group 0, Index 1, Command STATUS, Data 2{"StatusFWR":{"Version":"5.10.0","BuildDateTime":"2017-12-29T11:40:24","Boot":4,"Core":"2_3_0","SDK":"1.5.3(aec24ac9)"}}
[10-51-2018 14:46:56][ID-1][STAP-1][CONTROLEER] Controleer verbinding | PROBEER => 3
[10-51-2018 14:46:56][ID-1][STAP-1][CONTROLEER] FOUT: Apparaat heeft niet gereageerd! | MSG => JSON FOUT => 4: Syntax error
Kopieer de hele foutmelding en plak deze in een nieuwe bevinding op GitHUB. Op de een of andere manier gereageerde de Tasmota Firmware met een onjuiste JSON string, welke verwerkt dient te worden in TasmoAdmin. 
JSON Antwoord => Status, Data Size 1, Data 213:46:56 RSL: Group 0, Index 1, Command STATUS, Data 2{"StatusFWR":{"Version":"5.10.0","BuildDateTime":"2017-12-29T11:40:24","Boot":4,"Core":"2_3_0","SDK":"1.5.3(aec24ac9)"}}

## Steps to reproduce

> First update in second dropdown menu of Tasmoadmin page. Then select automatic update, select the device and update, now this error is coming

**Comment by reloxx13** [comment]
noo, this is compatibility issue, tasmota 5.10.0 has a very well wrong formatted json response.

would suggest to update by hand once, versions above 5.10.0 are working.


will be fixed in upcoming v1.1.1

**Comment by frenck** [comment]
This has been fixed upstream, the add-on needs to update.

**Comment by frenck** [comment]
A new version of the add-on has been released, which includes the latest version of TasmoAdmin.

**Comment by HFeenstra** [comment]
Thanks guys! That did the trick indeed. Also found out on my side that I had a port failure in my docker settings. 

Sorry but thanks!
