### ISSUE TITLE
403 error in hassio on RasPi

### ISSUE THREAD

**Issue by alekseyn1** [hassio-addons/addon-tasmoadmin#60]
# Problem/Motivation
Can not update firmware on any devices in hassio

## Expected behavior

.bin file should be available to the device

## Actual behavior

403 error in hassio on RasPi when getting the .bin file during the update of the device

## Steps to reproduce

Start the update (in auto mode) copy the url that shows in the log to test.
Plug into the browser and see the error

Hello,
Apologies if this has been discussed before.
Trying to use the latest Hassio on RasPi to upgrade devices.
used an automated and manual methods. Every option I use - update fails.

When trying to access the bin location using a browser
https://CEN.CORED.org:9541/data/firmwares/tasmota.bin
I am getting 403 (forbidden) error.

Any way to fix this?

**Comment by Geoff571** [comment]
I'm seeing the same problem when trying to download the latest firmware from the Tasmota OTA server. I think the issue is that the binaries have moved since Tasmota v7, the path is constructed wrongly.
Logs from the Tasmota console:
```
16:45:37 MQT: Teckin-SP23-11/stat/RESULT = {"OtaUrl":"http://thehackbox.org:9541/**data/firmwares**/tasmota.bin"}
16:45:37 MQT: Teckin-SP23-11/stat/RESULT = {"Upgrade":"Version 6.6.0 from http://thehackbox.org:9541/data/firmwares/tasmota.bin"}
16:45:40 HTP: Web server stopped
16:45:40 HTP: Web server active on TSP23-11 with IP address 192.168.1.61
16:45:42 HTP: Web server stopped
16:45:42 HTP: Web server active on TSP23-11 with IP address 192.168.1.61
16:45:44 HTP: Web server stopped
16:45:45 HTP: Web server active on TSP23-11 with IP address 192.168.1.61
16:45:46 HTP: Web server stopped
16:45:47 HTP: Web server active on TSP23-11 with IP address 192.168.1.61
16:45:49 HTP: Web server stopped
16:45:49 HTP: Web server active on TSP23-11 with IP address 192.168.1.61
16:45:51 MQT: Teckin-SP23-11/stat/UPGRADE = Failed HTTP error: connection refused
```
Logs from TasmoAdmin:

```
[05-01-2020 15:45:32][GLOBAL] Start update process
[05-01-2020 15:45:32][ID-4][STEP-2][GLOBAL] Start Step 2
[05-01-2020 15:45:32][ID-4][STEP-2][CHECK] Check Connection | TRY => 1
[05-01-2020 15:45:32][ID-4][STEP-2][CHECK] Connection Successfully! | Current Version => 6.6.0(release-sonoff)
[05-01-2020 15:45:32][ID-4][STEP-2][OTAURL] Set OTA URL for Firmware => NEW FW
[05-01-2020 15:45:32][ID-4][STEP-2][OTAURL] OTA Url => http://thehackbox.org:9541/data/firmwares/tasmota.bin
[05-01-2020 15:45:32][ID-4][STEP-1][OTAURL] OTA URL set for Firmware => NEW FW
[05-01-2020 15:45:32][ID-4][STEP-2][UPDATE] Trigger device update...
[05-01-2020 15:45:32][ID-4][STEP-2][UPDATE] Device update triggered
[05-01-2020 15:45:32][ID-4][STEP-2][CHECK UPDATE] Wait for update | Seconds => 60
[05-01-2020 15:46:33][ID-4][STEP-2][DONE] ============= Update done! =============
```
The new location for the Tasmota OTA files are [https://thehackbox.org/tasmota/release/](https://thehackbox.org/tasmota/release/)

**Comment by lociii** [comment]
Still valid.

**Comment by alekseyn1** [comment]
Has this been resolved?

**Comment by alekseyn1** [comment]
Updates over SSL do not seem to be supported. Thank you @SxthGear. For anyone who will find this issue: 
1. Disable SSL in the addon config ("ssl: false")
2. Restart addon
3. During addon Update command untick the "OTA use SSL" (tested with 'Automatic')
should work after that
