### ISSUE TITLE
ERROR TasmoAdmin does not install

### ISSUE THREAD

**Issue by simonunzio** [hassio-addons/addon-tasmoadmin#61]
Hi all,
seems to want the pull of the image from the wrong repo.
I tried from SSH, to give the command hassio addons remove TasmoAdmin, but it says that the component is not installed.
I don't know if any files have been hung from an incorrect installation, or if they are repo.

`19-12-14 15:57:45 INFO (SyncWorker_5) [hassio.docker.interface] Pull image hassioaddons/sonweb-armv7 tag 0.8.4.
19-12-14 15:57:47 ERROR (SyncWorker_5) [hassio.docker.interface] Can't install hassioaddons/sonweb-armv7:0.8.4 -> 500 Server Error: Internal Server Error ("readlink /mnt/data/docker/overlay2/l: invalid argument").`

![image](https://user-images.githubusercontent.com/50205427/70851413-fa351f80-1e94-11ea-8e4a-68262a3bc7a0.png)

![image](https://user-images.githubusercontent.com/50205427/70851416-0f11b300-1e95-11ea-88b0-9fcd65bc66b3.png)

**Comment by frenck** [comment]
This is not an add-on issue.

`readlink /mnt/data/docker/overlay2/l: invalid argument`

This indicates your Docker file system got corrupted.

run `hassio su repair`, get your self a cup a coffee while awaiting that to finish.
