### ISSUE TITLE
0.8.4 addon not show in side bar

### ISSUE THREAD

**Issue by pepeEL** [hassio-addons/addon-tasmoadmin#62]
# Problem/Motivation

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

Hi
I installed latest version tasmoadmin on my hassio. But it is not show in sidebar .... Why ?

**Comment by sinclairpaul** [comment]
Will assume you mean the Ingress show in sidebar option, which this addon does not support.

Duplicate of #59 #57 #54 #47 #44
