### ISSUE TITLE
Autoscan error

### ISSUE THREAD

**Issue by zuhair68** [hassio-addons/addon-tasmoadmin#64]
TasmoAdmin was successfully installed and started with no errors. When running Autoscan I get this error :
`Recoverable fatal error: Object of class stdClass could not be converted to string in /var/www/tasmoadmin/tasmoadmin/includes/Sonoff.php on line 1037`

**Config:**
`{
  "ssl": false,
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem",
  "log_level": "error"
}`

**This is the log:**

`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-tasmoadmin: applying... 
[fix-attrs.d] 01-tasmoadmin: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Hass.io Add-on: TasmoAdmin
 Centrally manage all your Sonoff-Tasmota devices
-----------------------------------------------------------
 Add-on version: 0.8.4
 You are running the latest version of this add-on.
 System: HassOS 3.7  (armv7 / raspberrypi3)
 Home Assistant version: 0.103.5
 Supervisor version: 193
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to ERROR
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] tasmoadmin.sh: executing... 
[cont-init.d] tasmoadmin.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
`

Adding the devices manually works OK

**Comment by frenck** [comment]
`Recoverable fatal error: Object of class stdClass could not be converted to string in /var/www/tasmoadmin/tasmoadmin/includes/Sonoff.php on line 1037`

This is an issue with the TasmoAdmin application that this add-on uses. Please report this issue @ the TasmoAdmin project. Thanks 👍
