### ISSUE TITLE
update to v1.6.4-beta2

### ISSUE THREAD

**Issue by pepeEL** [hassio-addons/addon-tasmoadmin#66]
# Problem/Motivation

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

Hi
Is any chance to update to version v1.6.4-beta2 ?

**Comment by sinclairpaul** [comment]
It is tagged as a pre-release, so generally the addons are not updated until a release is issued.  Unless there is a major issue that needs resolving?

**Comment by frenck** [comment]
We don't ship betas.
If there is an urgent fix needed, a stable (patch) release should be issued by the upstream project.
