### ISSUE TITLE
Doesn't find devices that changed ip address

### ISSUE THREAD

**Issue by SylvainGa** [hassio-addons/addon-tasmoadmin#67]
# Problem/Motivation
After I had to reboot my router, some of my Tasmota devices changed ip address. Tasmoadmin still thinks they are at their old address and a scan network didn't fix it. Also, scan network only finds 7 out of my 50+ devices. I was expecting it to find all the devices. Devices are up and running and available in Home Assistant.

> (Why the issue was filed)
Need to know how to clean its database
## Expected behavior
Find the devices at their new ip address

> (What you expected to happen)
Devices would be found at their new addresses after a rescan

## Actual behavior
Stays at their old ip addresses

> (What actually happened)
Stays at their old ip addresses

## Steps to reproduce
Change a device ip address and launch tasmoadmin

> (How can someone else make/see it happen)
See above

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by SylvainGa** [comment]
I guess I should mention this:

 Add-on version: 0.9.0
 You are running the latest version of this add-on.
 System: Raspbian GNU/Linux 10 (buster)  (armv7 / raspberrypi3)
 Home Assistant version: 0.104.3
 Supervisor version: 195

**Comment by SylvainGa** [comment]
I manually removed the unreachable (according to tasmoadmin) devices and redid a scan. Some where found, but not all. I uninstalled the plugin and reinstalled it to start fresh. After a rescan, they were all back.

**Comment by frenck** [comment]
This is not something I can provide a solution for. Add-ons wrap existing applications, in this case, TasmoAdmin. 

Please report your issue/feature request upstream: <https://github.com/reloxx13/TasmoAdmin>

Thanks 👍
