### ISSUE TITLE
Fresh TasmoAdmin install on Hass.io does not start

### ISSUE THREAD

**Issue by Skydev0h** [hassio-addons/addon-tasmoadmin#68]
# Problem/Motivation

> Unable to start TasmoAdmin addon at all

## Expected behavior

> Clearly the addon should start and work

## Actual behavior

> The addon fails to start up. 

Trace logs follow:
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-tasmoadmin: applying... 
[fix-attrs.d] 01-tasmoadmin: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 

-----------------------------------------------------------
 Hass.io Add-on: TasmoAdmin
 Centrally manage all your Sonoff-Tasmota devices
-----------------------------------------------------------
 Add-on version: 0.9.0
 You are running the latest version of this add-on.
 System: Ubuntu 16.04.6 LTS  (aarch64 / odroid-c2)
 Home Assistant version: 0.105.2
 Supervisor version: 199
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to TRACE
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[11:30:18] TRACE: bashio::config.true: ssl
[11:30:18] TRACE: bashio::config: ssl
[11:30:18] TRACE: bashio::jq: /data/options.json if (.ssl == null) then
            null
        elif (.ssl | type == "string") then
            .ssl // empty
        elif (.ssl | type == "boolean") then
            .ssl // false
        elif (.ssl | type == "array") then
            if (.ssl == []) then
                empty
            else
                .ssl[]
            end
        elif (.ssl | type == "object") then
            if (.ssl == {}) then
                empty
            else
                .ssl
            end
        else
            .ssl
        end
[11:30:18] TRACE: bashio::var.true: false
[11:30:18] TRACE: bashio::config.true: ssl
[11:30:18] TRACE: bashio::config: ssl
[11:30:19] TRACE: bashio::jq: /data/options.json if (.ssl == null) then
            null
        elif (.ssl | type == "string") then
            .ssl // empty
        elif (.ssl | type == "boolean") then
            .ssl // false
        elif (.ssl | type == "array") then
            if (.ssl == []) then
                empty
            else
                .ssl[]
            end
        elif (.ssl | type == "object") then
            if (.ssl == {}) then
                empty
            else
                .ssl
            end
        else
            .ssl
        end
[11:30:19] TRACE: bashio::var.true: false
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] tasmoadmin.sh: executing... 
[11:30:19] TRACE: bashio::fs.directory_exists: /data/sonweb
[11:30:19] TRACE: bashio::fs.directory_exists: /data/tasmoadmin
[11:30:19] DEBUG: Symlinking data directory to persistent storage location...
rm: can't remove '/var/www/tasmoadmin/tasmoadmin/data/firmwares': Invalid argument
rm: can't remove '/var/www/tasmoadmin/tasmoadmin/data/updates': Invalid argument
[cont-init.d] tasmoadmin.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

When starting up I can see following information in `docker ps`:
```
CONTAINER ID        IMAGE                                           COMMAND                  CREATED             STATUS              PORTS                    NAMES
afda4384616d        hassioaddons/sonweb-aarch64:0.9.0               "/init"                  5 seconds ago       Up 1 second         0.0.0.0:9541->9541/tcp   addon_a0d7b954_sonweb
```

## Steps to reproduce

> All information about versions of software and hardware used are compactly present in the log. The hass.io was minimally configured (just created user and tried to install needed addons). Only Configurator was installed before trying to install and start TasmoAdmin. First time it failed to startup because of `ssl` enabled and missing cert, after disabling `ssl` this happened.

Configuration:
```yaml
ssl: false
certfile: fullchain.pem
keyfile: privkey.pem
log_level: trace
```

**Comment by mahlbom** [comment]
Hi,

I have the same problem as above. I know it's not helping to solve the problem. But only saying that more people have the problem.

**Comment by afyfe** [comment]
yes, me too unfortunately i have this issue

**Comment by janicektrnecka** [comment]
Hello, another one affected. It seems like its a general issue, since other plugins have trouble to run ui / or access the ui theough browser

**Comment by EpicLPer** [comment]
Same problem here. Mine gets stuck at `[17:06:35] INFO: Starting NGinx server...` and won't go further than that.

**Comment by CarlosGS** [comment]
Yep, not working here either

**Comment by Foguet** [comment]
Another with the same problem here :(

**Comment by blackc69** [comment]
I also have the issue. I do not see a place to enter the configuration on the add-on page.

ssl: false
certfile: fullchain.pem
keyfile: privkey.pem
log_level: trace

**Comment by blackc69** [comment]
I did find where to enter the config. I did not realize it was a menu option now. I still cannot get the add-on to start due to a connection time out

**Comment by DanielPiccoli** [comment]
upgraded to hassOS 4.9 now tasmoadmin wont start.

**Comment by prime23-gareth** [comment]
Yep same here :(

**Comment by andbur** [comment]
same problem
GassOS 4.10
TasmoAdmin 0.11.0
Set to >Start on boot<
Does nit start on boot#Pressing Start button
Green circle on upper RH corner
OPEN WEB UI - result - >This site can't be reached<

Same on Windows 10, IPAD - Android

**Comment by andbur** [comment]
Got it working by settint >ssl< entry in configuration to >false<

**Comment by pierow2k** [comment]
Thanks @andbur - Disabled SSL and it appears to be working now.  

![TasmoAdmin_SSL-480x325](https://user-images.githubusercontent.com/9472998/86696716-539ca180-bfd3-11ea-9dd2-496a2d4f04cb.jpg)

**Comment by denisjoshua** [comment]
I have update also and I have same problem... it's stop at:

```
Add-on: TasmoAdmin
 Centrally manage all your Sonoff-Tasmota devices
-----------------------------------------------------------
 Add-on version: 649ba29
 You are running the latest version of this add-on.
 System: Ubuntu 18.04.4 LTS  (amd64 / qemux86-64)
 Home Assistant Core: 0.112.4
 Home Assistant Supervisor: 228
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] tasmoadmin.sh: executing... 
[cont-init.d] tasmoadmin.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[09:54:28] INFO: Starting PHP-FPM server...
[09:54:29] INFO: Starting NGinx server...
```


![image](https://user-images.githubusercontent.com/32936800/87241789-cb7d2880-c426-11ea-9e6a-f8c11b4bb5a3.png)

**Comment by mattveldhuis** [comment]
Same issue here.  

When I try to open the WebUI, it says: could not read MyConfig.json
My log file is below.

`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-tasmoadmin: applying... 
[fix-attrs.d] 01-tasmoadmin: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 

-----------------------------------------------------------
 Add-on: TasmoAdmin
 Centrally manage all your Sonoff-Tasmota devices
-----------------------------------------------------------
 Add-on version: 0.11.0
 You are running the latest version of this add-on.
 System: Ubuntu 20.04 LTS  (amd64 / qemux86-64)
 Home Assistant Core: 0.111.2
 Home Assistant Supervisor: 229
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to INFO
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] tasmoadmin.sh: executing... 
[cont-init.d] tasmoadmin.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[07:36:32] INFO: Starting PHP-FPM server...
[07:36:33] INFO: Starting NGinx server...`

**Comment by andre68723** [comment]
worthwhile alternative meanwhile - http://tasui.shantur.com ref https://github.com/IOTReboot/TasUI/

**Comment by amfetamin-pn** [comment]
same issue.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-tasmoadmin: applying... 
[fix-attrs.d] 01-tasmoadmin: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 

-----------------------------------------------------------
 Add-on: TasmoAdmin
 Centrally manage all your Sonoff-Tasmota devices
-----------------------------------------------------------
 Add-on version: 0.11.0
 You are running the latest version of this add-on.
 System: Raspbian GNU/Linux 10 (buster)  (armv7 / raspberrypi4)
 Home Assistant Core: 0.113.3
 Home Assistant Supervisor: 229
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to DEBUG
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] tasmoadmin.sh: executing... 
[11:17:11] DEBUG: Symlinking data directory to persistent storage location...
[cont-init.d] tasmoadmin.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[11:17:11] INFO: Starting PHP-FPM server...
[11:17:12] INFO: Starting NGinx server...

**Comment by sinclairpaul** [comment]
I see an original issue logged with errors in the logs:

`rm: can't remove '/var/www/tasmoadmin/tasmoadmin/data/firmwares': Invalid argument`
`rm: can't remove '/var/www/tasmoadmin/tasmoadmin/data/updates': Invalid argument`

The following comments all seem to be related to not being able to open the UI.  To confirm the message:

`INFO: Starting NGinx server...`

Is the expected last message in the log.  As the addon runs on a separate port, somethings to check:

 If you are using an external name resolution (e.g. duckdns) to access HA, how is this being resolved?, does your router support hairpin NAT?

Is the addon accessible via http/s://myipaddress:port (for example http://192.168.100.100:9541)

Please post the output from browser dev tools in case of no errors in the logs, and a 404 is presented.

As the original creator of the issue has not followed up, I would guess the original issue is resolved or abandoned.

**Comment by andbur** [comment]
Hi Paul,

I got TasmoAdmin working by using the following:

In Home Assitant - Select Supervisor - Add-ons TasmoAdmin

     herein - under Info - start - check the green active light on the 
upper right hand corner

                - under Configuration
                  1|     ssl: false
                  2|    certfile: fullchain.pem
                  3|     keyfile: privkey.pem

                  Note: SSL is not set up on my system so SSL set to 
false in the browser (in my case Firefox

                  Also check the Port TasmoAdmin is listening to - in my 
case unchanged 9541
                  thoughout your local network TasmoAdmin should be 
available using ip_of_the_PC_TasmoAdmin_is_installed_on:9541 or 
pressing  OPEN WEB UI on the TasmoAdmin Info page
                  in the browser (in my case Firefox) you do not need to 
enter https:// - just use the ip address and the port - eg 
192.168.100.100:9541

                - under Info - restart - check the green active light on 
the upper right hand corner

                - under Log - REFRESH and the following appears:

[s6-init] making user provided files available at 
/var/run/s6/etc...exited 0. [s6-init] ensuring user provided files have 
correct perms...exited 0. [fix-attrs.d] applying ownership & permissions 
fixes... [fix-attrs.d] 01-tasmoadmin: applying... [fix-attrs.d] 
01-tasmoadmin: exited 0. [fix-attrs.d] done. [cont-init.d] executing 
container initialization scripts... [cont-init.d] 00-banner.sh: 
executing... 
-----------------------------------------------------------Add-on: 
TasmoAdminCentrally manage all your Sonoff-Tasmota 
devices-----------------------------------------------------------Add-on 
version: 0.11.0You are running the latest version of this add-on.System: 
HassOS 4.11 (aarch64 / raspberrypi4-64)Home Assistant Core: 0.113.3Home 
Assistant Supervisor: 
229-----------------------------------------------------------Please, 
share the above information when looking for helpor support in, e.g., 
GitHub, forums or the Discord 
chat.-----------------------------------------------------------[cont-init.d] 
00-banner.sh: exited 0. [cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0. [cont-init.d] nginx.sh: 
executing... [cont-init.d] nginx.sh: exited 0. [cont-init.d] 
tasmoadmin.sh: executing... [cont-init.d] tasmoadmin.sh: exited 0. 
[cont-init.d] done. [services.d] starting services [services.d] done. 
[07:57:26] INFO: Starting PHP-FPM server...[07:57:27] INFO: Starting 
NGinx server


I have not activated the Hairpin Support on my router.
As seen above, I use just the ip address followed by the :9541, the 
standard port address, to access TasmoAdmin.

That is how I solved the problem on my system to get TasmoAdmin into 
working order.
I do hope that this info will help you.

Greetings from Johannesburg

Andreas



Am 04.08.2020 um 01:43 schrieb Paul Sinclair:

**Comment by noob4722019** [comment]
I was getting the stuck at nginx issue. Had ssl disabled. Also tried reinstalling, no luck.

Ended up changing the port to 9000 and it's not working.

I'm using hass.io on a VM.

**Comment by ipa64** [comment]
Tried everything sadly not working

**Comment by ipa64** [comment]
Finally it work, as nob4722019, need to change port to 9000
In fact I was expecting to have an icon on the sidebar, but no
Thanks for this tool

**Comment by btsimonh** [comment]
On a fresh install of HASS on RPI3, setting ssl:false allowed it to start - mine was defauklt to true?
BUT... ref issue https://github.com/hassio-addons/addon-tasmoadmin/issues/4 - the login page WITHIN hass does not work, whereas logging in to the port 9541 directly using the same user and pwd works fine.
