### ISSUE TITLE
Reasonable reset password or remove username control at all

### ISSUE THREAD

**Issue by jaakla** [hassio-addons/addon-tasmoadmin#69]
I have run several times to same issue: I add the addon, dont realize that the first screen which looks like normal Login is actually Register. Yes, there is the text "Register" but page/form looks exactly like Login: username and password fields with nothing else, totally weird for user registration. Also it is quite uncommon that a hassio addition asks any additional username/password in the first place. So I dont pay attention to the button text and strange logic, and enter some username and password, maybe it works. And it actually kind of works - I get in and I dont even recognize that actually I registered new user there and should remember it or add to my password database.

Now few weeks later next time, when I open the addition I am not so lucky to try same username and password, and I'm completely stuck. No way to remind or reset password. Usual TasmoAdmin way to reset password is to modify config file, but this not possible with the hassio module AFAIK?

Removal and re-addign the module is also quite annoying, I need to recreate configs. Even adding Tasmota devices is quite involved, scan is slow and does  not even find my device, only works if my scan range is just 1 correct IP address, finding this one requires scanning in DHCP server management etc.

**Comment by frenck** [comment]
This is a bad design on the application end, I 💯 % agree.

However, add-ons wrap existing applications. Please report the issue @ TasmoAdmin. Thanks! 👍
