### ISSUE TITLE
Trouble adding device

### ISSUE THREAD

**Issue by rogle** [hassio-addons/addon-tasmoadmin#7]
# Problem/Motivation

> Adding device by IP created error message requesting error message be posted

## Expected behavior

> assist programer troubleshoot

## Actual behavior

> Autoscan did not find this sonoff device after approx 100 scans. Tried add device with IP and received this error message.
Device not found

JSON ERROR => 4: Syntax error
Please copy the whole error message and copy it in a new issue on GitHub. Somehow the Tasmota Firmware answered a wrong formatted JSON string which needs to get adjusted in SonWEB.
JSON Answer => {"Status":{"Module":1,"FriendlyName":"Sonoff","Topic":"sonoff01","ButtonTopic":"0","Power":1,"PowerOnState":3,"LedState":1,"SaveData":1,"SaveState":1,"ButtonRetain":0,"PowerRetain":0},"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://domus1:80/api/arduino/sonoff01.ino.bin","Uptime":"0T00:37:14","Sleep":0,"BootCount":917,"SaveCount":2215,"SaveAddress":"FA000"},"StatusFWR":{"Version":"5.12.0","BuildDateTime":"2018-02-14T21:46:27","Boot":6,"Core":"2_4_0","SDK":"2.1.0(deb1901)"},"StatusLOG":{"SerialLog":2,"WebLog":2,"SysLog":0,"LogHost":"\\192.168.1.156\home\robb\Deskto","LogPort":514,"SSId1":"rowan","SSId2":"rowanotr","TelePeriod":300,"SetOption":"00000009"},"StatusMEM":{"ProgramSize":509,"Free":492,"Heap":19,"ProgramFlashSize":1024,"FlashSize":1024,"FlashMode":3},"StatusNET":{"Hostname":"sonoff01-7958","IPAddress":"192.168.1.50","Gateway":"192.168.1.2","Subnetmask":"255.255.255.0","DNSServer":"192.168.1.2","Mac":"EC:FA:BC:15:1F:16","Webserver":2,"WifiConfig":2},"StatusMQT":{"MqttHost":"192.168.1.14","MqttPort":1883,"MqttClientMask":"sonoffdev1","MqttClient":"sonoffdev1","MqttUser":"ogee","MAX_PACKET_SIZE":1000,"KEEPALIVE":15},"StatusTIM":{"UTC":"Tue Jun 12 18:40:58 2018","Local":"Tue Jun 12 19:40:58 2018","StartDST":"Sun Mar 25 02:00:00 2018","EndDST":"Sun Oct 28 03:00:00 2018","Timezone":1},"StatusSNS":{"Time":"2018-06-12T19:40:58"},"StatusSTS":{"Time":"2018-06-12T19:40:58","Uptime":"0T00:37:14","Vcc":3.465,"POWER":"ON","Wifi":{"AP":1,"SSId":"rowan","RSSI":66,"APMac":"60:38:E0:B2:8B:71"}}}

×

## Steps to reproduce

> unknown

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by reloxx13** [comment]
Dude, whats up with your loghost?

Its breaking teh json, is it valid?
"LogHost": "\\192.168.1.156\home\robb\Deskto",

shouldnt it be 
"LogHost": "http://192.168.1.156/home/robb/Deskto",

Pls check what is configured on the device

**Comment by frenck** [comment]
This is a user configuration error on the specific device.
Closing this issue, since it is not caused or related to the add-on.
