### ISSUE TITLE
How can I use TasmoAdmin without an SSL certificate?

### ISSUE THREAD

**Issue by SteveRMann** [hassio-addons/addon-tasmoadmin#70]
# Problem/Motivation

> (Why the issue was filed)
http://192.168.1.60:9541/ "connection refused"
## Expected behavior

> (What you expected to happen)
I would like to see my TasmoAdmin again
## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)
My system crashed and I had to reinstall everything, including TasmoAdmin.  In the config, I set ssl to false.

```
ssl: false
certfile: fullchain.pem
keyfile: privkey.pem

```
I do not have either .pem file but they are required, so I left them unchanged.

How can I use TasmoAdmin without an SSL certificate?

**Comment by sinclairpaul** [comment]
Can you post the addon startup logs?

**Comment by klaw81** [comment]
I encountered the same problem - possibly for the same reason. When attempting to launch the Web UI, it gives a "homeassistant.local refused to connect" error.
 
I do not have an SSL certificate (yet) so the certfile and keyfile will understandably not be found.

My add-on config file is set to the defaults, except I set SSL to false.

Startup logs:
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-tasmoadmin: applying... 
[fix-attrs.d] 01-tasmoadmin: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: TasmoAdmin
 Centrally manage all your Sonoff-Tasmota devices
-----------------------------------------------------------
 Add-on version: 0.10.0
 There is an update available for this add-on!
 Latest add-on version: null
 Please consider upgrading as soon as possible.
 System: HassOS 3.13  (amd64 / qemux86-64)
 Home Assistant Core: 0.109.1
 Home Assistant Supervisor: 220
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] tasmoadmin.sh: executing... 
[cont-init.d] tasmoadmin.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[16:57:59] INFO: Starting PHP-FPM server...
[services.d] done.
[16:57:59] INFO: Starting NGinx server...

Update: after a 15 second delay at the error screen, the page launched - not sure why it took so long.....

**Comment by fufs** [comment]
If you're using ufw make sure to make a rule for that port ("sudo ufw allow 9541")

**Comment by frenck** [comment]
No response from the original reporter in over a month. Closing issue.
