### ISSUE TITLE
Some devices start rebooting while being viewed on Devices > List

### ISSUE THREAD

**Issue by Vorta** [hassio-addons/addon-tasmoadmin#72]
# Problem/Motivation

I've added 9 devices to TasmoAdmin, 4 of them continuously reboot while viewing Devices > List page of TasmoAdmin

## Expected behavior

No reboots of Tasmota devices.

## Actual behavior

Bootloop.

## Steps to reproduce

Add devices over autoscan without changing anything that autoscan detects. Open Devices >List.

## Logs
Restart Reason:
```json
{
    "RestartReason": {
        "Exception": 0,
        "Reason": "Exception",
        "EPC": [
            "e003f004",
            "00000000",
            "00000000"
        ],
        "EXCVADDR": "00000000",
        "DEPC": "00000000",
        "CallChain": [
            "40240743",
            "40000f49",
            "40000f49",
            "40000e19",
            "40001878",
            "40105865",
            "4010586b",
            "401002ac",
            "40100f25",
            "40100f14",
            "40260de9",
            "40100e4c",
            "4000050c",
            "4000d4d2",
            "4027f185",
            "40246c80",
            "401036e6",
            "401002ac",
            "40100f25",
            "40100f14",
            "4000050c",
            "40103408",
            "40100e4c",
            "4000050c",
            "40247536",
            "4024715f",
            "4027f185",
            "40100e4c",
            "40246d4a",
            "402475e1",
            "40246d4a"
        ]
    }
}
```

**Comment by ascillato** [comment]
Hi, that is not a problem with Tasmoadmin add on. That is a bad flashing issue of your devices. Please, address this to the Tasmota support chat. Thanks.

**Comment by Vorta** [comment]
I have tinkered with device settings and it is not a bad flashing issue. The devices which were rebooting had MQTT log level set to 2, while others had it on 0, which is the default. Once I set MQTT log levels back to 0 the devices stopped rebooting.

How is the combination of TasmoAdmin's queries with this log level setting causing reboots it is beyond me.
