### ISSUE TITLE
Tasmota firmware versions update

### ISSUE THREAD

**Issue by simfun** [hassio-addons/addon-tasmoadmin#73]
Hi,

there is a problem if i try to update all devices at once. As there are mixed versions (tasmota.bin, tasmota-sensors.bin, etc.) the update is done using only tasmota.bin for all.
And then there is a mess. Is there any way to recognize the correct version for any device?

**Comment by frenck** [comment]
Hi, thanks for opening up an issue, however, this is a functionality of TasmoAdmin itself, not the add-on.

Add-ons wrap existing applications for easy use. If there is an issue with the application itself, please report it to the upstream project. Thanks! 👍
