### ISSUE TITLE
TasmoAdmin fails to install under Hass.io add-on on qemux86-64 running on Proxmox hypervisor

### ISSUE THREAD

**Issue by dark-age** [hassio-addons/addon-tasmoadmin#74]
# Problem/Motivation

TasmoAdmin fails to install under Hass.io add-on menu running on qemux86-64 virtual machine.

System | Debian GNU/Linux 10 (buster)
Supervisor - Latest version 209

## Actual behavior

RROR (SyncWorker_19) [supervisor.docker.interface] Can't install hassioaddons/sonweb-amd64:0.10.0 -> 404 Client Error: Not Found ("no such image: hassioaddons/sonweb-amd64:0.10.0: No such image: hassioaddons/sonweb-amd64:0.10.0")

## Steps to reproduce

Open Hass.IO web interface and navigate to supervisor --> add-on store --> TasmoAdmin plugin install

## Proposed changes

Potential issue with docker image?

**Comment by frenck** [comment]
>  404 Client Error: Not Found 

This means there is not enough disk space left to complete the download, extract & install operation.

Please ensure you have enough disk space.

**Comment by dark-age** [comment]
Thank you!
