### ISSUE TITLE
Can't update the sonoff through TasmoAdmin

### ISSUE THREAD

**Issue by phcella** [hassio-addons/addon-tasmoadmin#76]
# Problem/Motivation
Tried to update my all sonoffs to the last version of tasmota

## Expected behavior
Update to the version

## Actual behavior
They don't update

## Steps to reproduce
On the screen to update:
OTA IP Server: I put my hassio IP
OTA Server Port: I didn't change (9541)
MINIMAL Firmware: Download from github the last version 8.2.0 (MINIMAL verion)
Full Firmware: The last firmawe 8.2.0 (BR Portuguese)

Click next and select all devices and next again.

Wait until the log show "[07-04-2020 12:29:27][ID-2][STEP-2][DONE] ============= Update done! ============="

I go back to tasmoadmin devices list and the sonoff didn't update

I attached some screenshots and the log after "update"

![Capturar](https://user-images.githubusercontent.com/20034679/78688905-23f2d600-78cc-11ea-8a2a-0a2296966763.PNG)
![log](https://user-images.githubusercontent.com/20034679/78688908-248b6c80-78cc-11ea-8617-5f287132b881.PNG)
[Log.txt](https://github.com/hassio-addons/addon-tasmoadmin/files/4445564/Log.txt)
![update](https://user-images.githubusercontent.com/20034679/78688915-25bc9980-78cc-11ea-909f-1519559849c8.PNG)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by phcella** [comment]
The first device (Sonoff Pow #0) is updated because I updeted it manually

**Comment by alekseyn1** [comment]
Do not mean to hijack this, but your issue could be related to another one. It was closed by a bot,  but it might explain what is happening. 

https://github.com/hassio-addons/addon-tasmoadmin/issues/60

**Comment by alekseyn1** [comment]
Also there is a suggestion to fix this issue here (please try)
https://github.com/reloxx13/TasmoAdmin/issues/331

> Apparently updates over SSL are not supported right now. You'll have to go into the addon config and disable SSL support for the addon and then untick the "OTA use SSL". It should work after that.

**Comment by phcella** [comment]
> Also there is a suggestion to fix this issue here (please try)
> [reloxx13/TasmoAdmin#331](https://github.com/reloxx13/TasmoAdmin/issues/331)
> 
> > Thank you @SxthGear . For anyone who will find this issue:
> 
> 1. Disable SSL in the addon config ("ssl: false")
> 2. Restart addon
> 3. During addon Update command untick the "OTA use SSL" (tested with 'Automatic')
>    should work after that

Thanks, it worked!!
