### ISSUE TITLE
Unable to Update TasmoAdmin from 0.10 to current version

### ISSUE THREAD

**Issue by DesertDwellerEv** [hassio-addons/addon-tasmoadmin#78]
# Problem/Motivation

> Tried to update TasmoAdmin

## Expected behavior

> Hassio Addon window for TA should display Update button

## Actual behavior

> 
![image](https://user-images.githubusercontent.com/53842308/79601786-3de7a200-809e-11ea-8f0b-9932f78b1c0b.png)

## Steps to reproduce

> Hassio Supervisor Page select TasmoAdmin

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by sinclairpaul** [comment]
You already have the latest release of the addon.

https://github.com/hassio-addons/addon-tasmoadmin/releases

**Comment by DesertDwellerEv** [comment]
Why does the list display a update button on the bottom?
[image: image.png]
Which displays
[image: image.png]
and Hassio/Supervisor displays v 0.10.0
[image: image.png]
Seems a bit confusing to me.

**Comment by sinclairpaul** [comment]
Unfortunately we cannot see your attachments (Likely email response to an issue).

If you mean this:

![image](https://user-images.githubusercontent.com/24625998/79623007-f980f400-80e7-11ea-9e33-f2a36fe21bc9.png)

Then it is an issue that will be resolved in the next release.

**Comment by DesertDwellerEv** [comment]
Correct.
