### ISSUE TITLE
Feature Request : Support base_url in config

### ISSUE THREAD

**Issue by devanl** [hassio-addons/addon-tasmoadmin#79]
# Problem/Motivation

> I would like to be able to configure the base_url so that this works through nginx proxy

## Expected behavior

> configured nginx to proxy location (/tasmoadmin) 

## Actual behavior

> the login redirects to root url (/login)

## Steps to reproduce

> In nginx server entry 
```
    location /tasmoadmin {
        proxy_pass        http://192.168.1.17:9541;
        proxy_redirect    off;
        proxy_buffering   off;
    }  
```

## Proposed changes
> add-on pane it would be nice to be able to add this to config as base_url

**Comment by frenck** [comment]
Sorry m8, this level of customization is considered out of scope.

I suggest running TasmotaAdmin directly if you want those types of customizations.

**Comment by devanl** [comment]
I believe TasmotaAdmin supports defining the base url with the environment variable TASMO_BASEURL. Is this not something that can be defined with a change to the config.json?  I admit I still haven’t figured out how that file is connected to everything. 

Regards,
Devan
