### ISSUE TITLE
How to add this to HA Core?

### ISSUE THREAD

**Issue by oywino** [hassio-addons/addon-tasmoadmin#80]
# Problem/Motivation

> It is somehow frustrating that all those fancy addons assume that everyone is running Hass.io
Well, some of us aren't. Therefore it would be nice to know if/how to install these addons for us that doesn't have a Supervisor Add-on Store.

## Expected behavior

> I was hoping for an explanation

## Actual behavior

> So far, not much.

## Steps to reproduce

> None

## Proposed changes

> Add a description on how to install the addon in HA Core.

**Comment by sinclairpaul** [comment]
You can't, the addons require the supervisor for management (for example the installation and upgrade process) and integration (such as security and services).

If they were just plain docker images, they wouldn't need to be managed as addons.
