### ISSUE TITLE
IR firmware should upgrade to ir firmware not generic

### ISSUE THREAD

**Issue by dns53** [hassio-addons/addon-tasmoadmin#81]
# Problem/Motivation

I have an IR Blaster running the tasmota-ir firmware.
I went through the upgrade wizard and this installed the generic tasmota firmware instead of sticking with the ir variant.

## Expected behavior

The tool should download different versions of the firmware if they are in use and apply that  variant if it is being used.

## Actual behavior

It currently applies the generic firmware always.

## Steps to reproduce

1. Have a device running a different variant of the firmware (ir, sensor, minimum, lite etc)
2. add the device to the tool
3. specify the ota server ip address
4. go to devices  > update > automatically download updates
5. select a device to apply updates

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by sinclairpaul** [comment]
The addon wraps the existing software, please log your issue upstream at https://github.com/reloxx13/TasmoAdmin

Thanks.
