### ISSUE TITLE
No status updates

### ISSUE THREAD

**Issue by fufs** [hassio-addons/addon-tasmoadmin#82]
# Problem/Motivation

> (Why the issue was filed)

The power state doesn't update and RSSI, version and runtime are stuck on loading
## Expected behavior

> (What you expected to happen)

All the info showing up
## Actual behavior

> (What actually happened)

As described
## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by sinclairpaul** [comment]
There really isn't much in this issue that anyone can help with.  With that said looking at the source application (which you will find here https://github.com/reloxx13/TasmoAdmin.git) the data appears to be rendered via client side Javascript.

I would suggest looking in your browser console for errors, as I would guess it cannot communicate with the devices.

I doubt very much this is anything to do with the addon itself.
