### ISSUE TITLE
This add-on is not easy to install

### ISSUE THREAD

**Issue by Czech-Lion** [hassio-addons/addon-tasmoadmin#91]
# Problem/Motivation

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by Czech-Lion** [comment]
the author says it is easy to install. It's not true.

**Comment by frenck** [comment]
Sorry to hear that. If you are in need for support, please use the support channels. Thanks 👍
