### ISSUE TITLE
Update Devices page always fetches from OTA server - ignores manually-entered firmware files

### ISSUE THREAD

**Issue by mrneutron42** [hassio-addons/addon-tasmoadmin#96]
# Problem/Motivation

Update Devices page ignores manually-entered firmware files - always uses Automatic firmware file selection
TasmoAdmin version 0.13.0

Home Assistant version 0.115.6
arch | x86_64
chassis | vm
dev | false
docker | true
docker_version | 19.03.11
hassio | true
host_os | HassOS 4.13
installation_type | Home Assistant OS
os_name | Linux
os_version | 5.4.63
python_version | 3.8.5
supervisor | 245
timezone | America/Chicago
version | 0.115.6
virtualenv | false

## Expected behavior

Expected manually-entered firmware files to be loaded, rather than fetching files from the Tasmota OTA firmware server.

## Actual behavior

The updater always goes out to the Tasmota OTA firmware server 172.30.33.0 and fetches firmware files, even if manually-entered firmware files are chosen.

## Steps to reproduce

Open Updater window, 
manually select a minimal and full firmware files from a local hard drive, 
click NEXT.
Select a Tasmota device to update and click the Start Update button.
You will see that the latest version of firmware is fetched from the Tasmota OTA firmware server, rather than loading the firmware files you manually selected.

## Proposed changes

Fix Update Devices functionality so it doesn't automatically fetch firmware from the Tasmota OTA firmware server, when firmware files have been manually entered.

![TasmoAdmin Update Devices window](https://user-images.githubusercontent.com/70338169/94942459-f2824e00-049b-11eb-8a23-0d90ad1d494a.PNG)
![TasmoAdmin fetches from web by default](https://user-images.githubusercontent.com/70338169/94942473-f6ae6b80-049b-11eb-8fcc-931b813a3520.PNG)

**Comment by sinclairpaul** [comment]
The addon wraps the existing software at https://github.com/reloxx13/TasmoAdmin.  You may be better asking you questions there.

With that said, the only way to update the devices is via OTA/HTTP download, you need to specify your IP in the OTA address.  I believe the browse dialogs allow you to upload local images to TasmoAdmin.

**Comment by mrneutron42** [comment]
Oh, ok.  Thanks for the redirect.
