### ISSUE TITLE
OTA Server IP uses Docker IP

### ISSUE THREAD

**Issue by duhow** [hassio-addons/addon-tasmoadmin#97]
# Problem/Motivation

> OTA Server IP was set to Docker IP instead of Internal URL

## Expected behavior

> On the update screen, have the wrong IP address placed, so Tasmota devices can't reach TasmoAdmin and don't update.

## Actual behavior

> Internal Docker IP 172.33.xx.xx was in place.

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> Try to load Home Assistant (Hass.io) settings and get the Internal URL / IP address

**Comment by frenck** [comment]
You can set the URL to use in the TasmoAdmin settings.
